// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_12__char_41__d97bb46a49493fa4eb0d9e6997c78f5c_Cube__char_46_SpawnTower_d210f503_3813_484b_9843_9b11650004a7 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_12__char_41__d97bb46a49493fa4eb0d9e6997c78f5c_Cube__char_46_SpawnTower_d210f503_3813_484b_9843_9b11650004a7;

		public static void Serialize(Cube__char_32___char_40_12__char_41__d97bb46a49493fa4eb0d9e6997c78f5c_Cube__char_46_SpawnTower_d210f503_3813_484b_9843_9b11650004a7 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_12__char_41__d97bb46a49493fa4eb0d9e6997c78f5c_Cube__char_46_SpawnTower_d210f503_3813_484b_9843_9b11650004a7 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_12__char_41__d97bb46a49493fa4eb0d9e6997c78f5c_Cube__char_46_SpawnTower_d210f503_3813_484b_9843_9b11650004a7
			(
			){};
		}
	}
}
