// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_20__char_41__cd4fc98a75f2b754ca00dbec3055ed9b_Cube__char_46_SpawnTower_56f210aa_e8bb_43e5_b2f7_7985816b822f : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_20__char_41__cd4fc98a75f2b754ca00dbec3055ed9b_Cube__char_46_SpawnTower_56f210aa_e8bb_43e5_b2f7_7985816b822f;

		public static void Serialize(Cube__char_32___char_40_20__char_41__cd4fc98a75f2b754ca00dbec3055ed9b_Cube__char_46_SpawnTower_56f210aa_e8bb_43e5_b2f7_7985816b822f commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_20__char_41__cd4fc98a75f2b754ca00dbec3055ed9b_Cube__char_46_SpawnTower_56f210aa_e8bb_43e5_b2f7_7985816b822f Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_20__char_41__cd4fc98a75f2b754ca00dbec3055ed9b_Cube__char_46_SpawnTower_56f210aa_e8bb_43e5_b2f7_7985816b822f
			(
			){};
		}
	}
}
