// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_53__char_41__7e827d2f3d367ae49b638f97bd525f6c_Cube__char_46_SpawnTower_3d572e71_ea0a_4213_8b59_2a07fbfa4d49 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_53__char_41__7e827d2f3d367ae49b638f97bd525f6c_Cube__char_46_SpawnTower_3d572e71_ea0a_4213_8b59_2a07fbfa4d49;

		public static void Serialize(Cube__char_32___char_40_53__char_41__7e827d2f3d367ae49b638f97bd525f6c_Cube__char_46_SpawnTower_3d572e71_ea0a_4213_8b59_2a07fbfa4d49 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_53__char_41__7e827d2f3d367ae49b638f97bd525f6c_Cube__char_46_SpawnTower_3d572e71_ea0a_4213_8b59_2a07fbfa4d49 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_53__char_41__7e827d2f3d367ae49b638f97bd525f6c_Cube__char_46_SpawnTower_3d572e71_ea0a_4213_8b59_2a07fbfa4d49
			(
			){};
		}
	}
}
