// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_69__char_41__03576f38473d7444aa0b0dfd6f5ae6b6_Cube__char_46_SpawnTower_ec1070d2_893f_4f7b_90ec_059331280c0a : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_69__char_41__03576f38473d7444aa0b0dfd6f5ae6b6_Cube__char_46_SpawnTower_ec1070d2_893f_4f7b_90ec_059331280c0a;

		public static void Serialize(Cube__char_32___char_40_69__char_41__03576f38473d7444aa0b0dfd6f5ae6b6_Cube__char_46_SpawnTower_ec1070d2_893f_4f7b_90ec_059331280c0a commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_69__char_41__03576f38473d7444aa0b0dfd6f5ae6b6_Cube__char_46_SpawnTower_ec1070d2_893f_4f7b_90ec_059331280c0a Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_69__char_41__03576f38473d7444aa0b0dfd6f5ae6b6_Cube__char_46_SpawnTower_ec1070d2_893f_4f7b_90ec_059331280c0a
			(
			){};
		}
	}
}
