// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_111__char_41__61a7f6a6abde5fb40bb74fb483fc16d2_Cube__char_46_SpawnTower_6307a5f3_ce59_4d57_9e8f_f5c006a6a69b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_111__char_41__61a7f6a6abde5fb40bb74fb483fc16d2_Cube__char_46_SpawnTower_6307a5f3_ce59_4d57_9e8f_f5c006a6a69b;

		public static void Serialize(Cube__char_32___char_40_111__char_41__61a7f6a6abde5fb40bb74fb483fc16d2_Cube__char_46_SpawnTower_6307a5f3_ce59_4d57_9e8f_f5c006a6a69b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_111__char_41__61a7f6a6abde5fb40bb74fb483fc16d2_Cube__char_46_SpawnTower_6307a5f3_ce59_4d57_9e8f_f5c006a6a69b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_111__char_41__61a7f6a6abde5fb40bb74fb483fc16d2_Cube__char_46_SpawnTower_6307a5f3_ce59_4d57_9e8f_f5c006a6a69b
			(
			){};
		}
	}
}
