// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_89__char_41__45b2df7bc87f2794f87da163fd88fc86_Cube__char_46_SpawnTower_36a1bfd7_041f_401b_87ee_58f6f7526455 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_89__char_41__45b2df7bc87f2794f87da163fd88fc86_Cube__char_46_SpawnTower_36a1bfd7_041f_401b_87ee_58f6f7526455;

		public static void Serialize(Cube__char_32___char_40_89__char_41__45b2df7bc87f2794f87da163fd88fc86_Cube__char_46_SpawnTower_36a1bfd7_041f_401b_87ee_58f6f7526455 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_89__char_41__45b2df7bc87f2794f87da163fd88fc86_Cube__char_46_SpawnTower_36a1bfd7_041f_401b_87ee_58f6f7526455 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_89__char_41__45b2df7bc87f2794f87da163fd88fc86_Cube__char_46_SpawnTower_36a1bfd7_041f_401b_87ee_58f6f7526455
			(
			){};
		}
	}
}
