// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_23__char_41__d983698f9c44d94458d2818909e7e5ce_Cube__char_46_SpawnTower_2bce5f24_b02e_47bf_b090_d4d70ce26045 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_23__char_41__d983698f9c44d94458d2818909e7e5ce_Cube__char_46_SpawnTower_2bce5f24_b02e_47bf_b090_d4d70ce26045;

		public static void Serialize(Cube__char_32___char_40_23__char_41__d983698f9c44d94458d2818909e7e5ce_Cube__char_46_SpawnTower_2bce5f24_b02e_47bf_b090_d4d70ce26045 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_23__char_41__d983698f9c44d94458d2818909e7e5ce_Cube__char_46_SpawnTower_2bce5f24_b02e_47bf_b090_d4d70ce26045 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_23__char_41__d983698f9c44d94458d2818909e7e5ce_Cube__char_46_SpawnTower_2bce5f24_b02e_47bf_b090_d4d70ce26045
			(
			){};
		}
	}
}
