// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_52__char_41__9394aef9a8dcd4847855d4670db9a9e0_Cube__char_46_SpawnTower_f80e5f26_d2d5_4de2_b705_bf736fbf175f : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_52__char_41__9394aef9a8dcd4847855d4670db9a9e0_Cube__char_46_SpawnTower_f80e5f26_d2d5_4de2_b705_bf736fbf175f;

		public static void Serialize(Cube__char_32___char_40_52__char_41__9394aef9a8dcd4847855d4670db9a9e0_Cube__char_46_SpawnTower_f80e5f26_d2d5_4de2_b705_bf736fbf175f commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_52__char_41__9394aef9a8dcd4847855d4670db9a9e0_Cube__char_46_SpawnTower_f80e5f26_d2d5_4de2_b705_bf736fbf175f Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_52__char_41__9394aef9a8dcd4847855d4670db9a9e0_Cube__char_46_SpawnTower_f80e5f26_d2d5_4de2_b705_bf736fbf175f
			(
			){};
		}
	}
}
