// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_62__char_41__aa9ac05b2611ca54f9668af9c3d72dd5_Cube__char_46_SpawnTower_64fc8b58_5f3f_4cf4_b501_f929a3153466 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_62__char_41__aa9ac05b2611ca54f9668af9c3d72dd5_Cube__char_46_SpawnTower_64fc8b58_5f3f_4cf4_b501_f929a3153466;

		public static void Serialize(Cube__char_32___char_40_62__char_41__aa9ac05b2611ca54f9668af9c3d72dd5_Cube__char_46_SpawnTower_64fc8b58_5f3f_4cf4_b501_f929a3153466 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_62__char_41__aa9ac05b2611ca54f9668af9c3d72dd5_Cube__char_46_SpawnTower_64fc8b58_5f3f_4cf4_b501_f929a3153466 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_62__char_41__aa9ac05b2611ca54f9668af9c3d72dd5_Cube__char_46_SpawnTower_64fc8b58_5f3f_4cf4_b501_f929a3153466
			(
			){};
		}
	}
}
