// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_100__char_41__dad5a18e3f4d28c4d86d385b82aaa23f_Cube__char_46_SpawnTower_8b172a72_47e3_4df0_b28d_159eced1bf17 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_100__char_41__dad5a18e3f4d28c4d86d385b82aaa23f_Cube__char_46_SpawnTower_8b172a72_47e3_4df0_b28d_159eced1bf17;

		public static void Serialize(Cube__char_32___char_40_100__char_41__dad5a18e3f4d28c4d86d385b82aaa23f_Cube__char_46_SpawnTower_8b172a72_47e3_4df0_b28d_159eced1bf17 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_100__char_41__dad5a18e3f4d28c4d86d385b82aaa23f_Cube__char_46_SpawnTower_8b172a72_47e3_4df0_b28d_159eced1bf17 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_100__char_41__dad5a18e3f4d28c4d86d385b82aaa23f_Cube__char_46_SpawnTower_8b172a72_47e3_4df0_b28d_159eced1bf17
			(
			){};
		}
	}
}
