// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_107__char_41__2a42754f43050944caa575f6614a4ce4_Cube__char_46_SpawnTower_e9f317f9_ef80_4e07_a224_58b029884079 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_107__char_41__2a42754f43050944caa575f6614a4ce4_Cube__char_46_SpawnTower_e9f317f9_ef80_4e07_a224_58b029884079;

		public static void Serialize(Cube__char_32___char_40_107__char_41__2a42754f43050944caa575f6614a4ce4_Cube__char_46_SpawnTower_e9f317f9_ef80_4e07_a224_58b029884079 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_107__char_41__2a42754f43050944caa575f6614a4ce4_Cube__char_46_SpawnTower_e9f317f9_ef80_4e07_a224_58b029884079 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_107__char_41__2a42754f43050944caa575f6614a4ce4_Cube__char_46_SpawnTower_e9f317f9_ef80_4e07_a224_58b029884079
			(
			){};
		}
	}
}
