// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_109__char_41__c86087bea558e7a4695a5f6e5919062b_Cube__char_46_SpawnTower_9119999c_7a01_4d47_a7a3_325bdf2663f4 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_109__char_41__c86087bea558e7a4695a5f6e5919062b_Cube__char_46_SpawnTower_9119999c_7a01_4d47_a7a3_325bdf2663f4;

		public static void Serialize(Cube__char_32___char_40_109__char_41__c86087bea558e7a4695a5f6e5919062b_Cube__char_46_SpawnTower_9119999c_7a01_4d47_a7a3_325bdf2663f4 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_109__char_41__c86087bea558e7a4695a5f6e5919062b_Cube__char_46_SpawnTower_9119999c_7a01_4d47_a7a3_325bdf2663f4 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_109__char_41__c86087bea558e7a4695a5f6e5919062b_Cube__char_46_SpawnTower_9119999c_7a01_4d47_a7a3_325bdf2663f4
			(
			){};
		}
	}
}
