// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_OnHover_d059d81d_990f_4266_9b43_28fdc813abbf : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_OnHover_d059d81d_990f_4266_9b43_28fdc813abbf;

		public static void Serialize(Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_OnHover_d059d81d_990f_4266_9b43_28fdc813abbf commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_OnHover_d059d81d_990f_4266_9b43_28fdc813abbf Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_OnHover_d059d81d_990f_4266_9b43_28fdc813abbf
			(
			){};
		}
	}
}
