// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_74__char_41__175faa9b8f01b8c4aa444a14a48d0016_Cube__char_46_SpawnTower_eeef5997_5f8d_41e1_b3fa_70a0631c39e0 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_74__char_41__175faa9b8f01b8c4aa444a14a48d0016_Cube__char_46_SpawnTower_eeef5997_5f8d_41e1_b3fa_70a0631c39e0;

		public static void Serialize(Cube__char_32___char_40_74__char_41__175faa9b8f01b8c4aa444a14a48d0016_Cube__char_46_SpawnTower_eeef5997_5f8d_41e1_b3fa_70a0631c39e0 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_74__char_41__175faa9b8f01b8c4aa444a14a48d0016_Cube__char_46_SpawnTower_eeef5997_5f8d_41e1_b3fa_70a0631c39e0 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_74__char_41__175faa9b8f01b8c4aa444a14a48d0016_Cube__char_46_SpawnTower_eeef5997_5f8d_41e1_b3fa_70a0631c39e0
			(
			){};
		}
	}
}
