// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_50__char_41__70c6b2d146f5f0049a2baaeae6c8b729_Cube__char_46_SpawnTower_fae0b873_a130_4148_a1e4_07eada4d0a78 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_50__char_41__70c6b2d146f5f0049a2baaeae6c8b729_Cube__char_46_SpawnTower_fae0b873_a130_4148_a1e4_07eada4d0a78;

		public static void Serialize(Cube__char_32___char_40_50__char_41__70c6b2d146f5f0049a2baaeae6c8b729_Cube__char_46_SpawnTower_fae0b873_a130_4148_a1e4_07eada4d0a78 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_50__char_41__70c6b2d146f5f0049a2baaeae6c8b729_Cube__char_46_SpawnTower_fae0b873_a130_4148_a1e4_07eada4d0a78 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_50__char_41__70c6b2d146f5f0049a2baaeae6c8b729_Cube__char_46_SpawnTower_fae0b873_a130_4148_a1e4_07eada4d0a78
			(
			){};
		}
	}
}
