// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_13__char_41__5b496a6e4afebf444a45fdb4cb14e724_Cube__char_46_SpawnTower_80ead4fc_9e66_4148_94f5_0c75141759c4 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_13__char_41__5b496a6e4afebf444a45fdb4cb14e724_Cube__char_46_SpawnTower_80ead4fc_9e66_4148_94f5_0c75141759c4;

		public static void Serialize(Cube__char_32___char_40_13__char_41__5b496a6e4afebf444a45fdb4cb14e724_Cube__char_46_SpawnTower_80ead4fc_9e66_4148_94f5_0c75141759c4 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_13__char_41__5b496a6e4afebf444a45fdb4cb14e724_Cube__char_46_SpawnTower_80ead4fc_9e66_4148_94f5_0c75141759c4 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_13__char_41__5b496a6e4afebf444a45fdb4cb14e724_Cube__char_46_SpawnTower_80ead4fc_9e66_4148_94f5_0c75141759c4
			(
			){};
		}
	}
}
