// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_31__char_41__67d56ec1b61a7a34593c59cb1c668e55_Cube__char_46_SpawnTower_427e9f83_027a_4159_af18_fd63b1d83e1a : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_31__char_41__67d56ec1b61a7a34593c59cb1c668e55_Cube__char_46_SpawnTower_427e9f83_027a_4159_af18_fd63b1d83e1a;

		public static void Serialize(Cube__char_32___char_40_31__char_41__67d56ec1b61a7a34593c59cb1c668e55_Cube__char_46_SpawnTower_427e9f83_027a_4159_af18_fd63b1d83e1a commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_31__char_41__67d56ec1b61a7a34593c59cb1c668e55_Cube__char_46_SpawnTower_427e9f83_027a_4159_af18_fd63b1d83e1a Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_31__char_41__67d56ec1b61a7a34593c59cb1c668e55_Cube__char_46_SpawnTower_427e9f83_027a_4159_af18_fd63b1d83e1a
			(
			){};
		}
	}
}
