// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_22__char_41__8c81c5f64e10eea41bd6e089ad3aebed_Cube__char_46_SpawnTower_42bd02ac_7dfe_4c56_8c15_d2945e84b6a5 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_22__char_41__8c81c5f64e10eea41bd6e089ad3aebed_Cube__char_46_SpawnTower_42bd02ac_7dfe_4c56_8c15_d2945e84b6a5;

		public static void Serialize(Cube__char_32___char_40_22__char_41__8c81c5f64e10eea41bd6e089ad3aebed_Cube__char_46_SpawnTower_42bd02ac_7dfe_4c56_8c15_d2945e84b6a5 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_22__char_41__8c81c5f64e10eea41bd6e089ad3aebed_Cube__char_46_SpawnTower_42bd02ac_7dfe_4c56_8c15_d2945e84b6a5 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_22__char_41__8c81c5f64e10eea41bd6e089ad3aebed_Cube__char_46_SpawnTower_42bd02ac_7dfe_4c56_8c15_d2945e84b6a5
			(
			){};
		}
	}
}
