// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_7__char_41__c477fdfcd87ca8f4984a250ee02a14f3_Cube__char_46_SpawnTower_26f7db7b_6e37_4044_99a7_a1c34b93fcdf : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_7__char_41__c477fdfcd87ca8f4984a250ee02a14f3_Cube__char_46_SpawnTower_26f7db7b_6e37_4044_99a7_a1c34b93fcdf;

		public static void Serialize(Cube__char_32___char_40_7__char_41__c477fdfcd87ca8f4984a250ee02a14f3_Cube__char_46_SpawnTower_26f7db7b_6e37_4044_99a7_a1c34b93fcdf commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_7__char_41__c477fdfcd87ca8f4984a250ee02a14f3_Cube__char_46_SpawnTower_26f7db7b_6e37_4044_99a7_a1c34b93fcdf Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_7__char_41__c477fdfcd87ca8f4984a250ee02a14f3_Cube__char_46_SpawnTower_26f7db7b_6e37_4044_99a7_a1c34b93fcdf
			(
			){};
		}
	}
}
