// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_65__char_41__4f82ec12b85d08746a48868ed4347d53_Cube__char_46_SpawnTower_e9579afd_09e1_44d0_b0e4_9a14286281cc : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_65__char_41__4f82ec12b85d08746a48868ed4347d53_Cube__char_46_SpawnTower_e9579afd_09e1_44d0_b0e4_9a14286281cc;

		public static void Serialize(Cube__char_32___char_40_65__char_41__4f82ec12b85d08746a48868ed4347d53_Cube__char_46_SpawnTower_e9579afd_09e1_44d0_b0e4_9a14286281cc commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_65__char_41__4f82ec12b85d08746a48868ed4347d53_Cube__char_46_SpawnTower_e9579afd_09e1_44d0_b0e4_9a14286281cc Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_65__char_41__4f82ec12b85d08746a48868ed4347d53_Cube__char_46_SpawnTower_e9579afd_09e1_44d0_b0e4_9a14286281cc
			(
			){};
		}
	}
}
