// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_119__char_41__9a87bba4a6733504fbe2bbb76f2ccd86_Cube__char_46_SpawnTower_d1271c91_a403_47e2_8f2b_a27170be60c5 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_119__char_41__9a87bba4a6733504fbe2bbb76f2ccd86_Cube__char_46_SpawnTower_d1271c91_a403_47e2_8f2b_a27170be60c5;

		public static void Serialize(Cube__char_32___char_40_119__char_41__9a87bba4a6733504fbe2bbb76f2ccd86_Cube__char_46_SpawnTower_d1271c91_a403_47e2_8f2b_a27170be60c5 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_119__char_41__9a87bba4a6733504fbe2bbb76f2ccd86_Cube__char_46_SpawnTower_d1271c91_a403_47e2_8f2b_a27170be60c5 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_119__char_41__9a87bba4a6733504fbe2bbb76f2ccd86_Cube__char_46_SpawnTower_d1271c91_a403_47e2_8f2b_a27170be60c5
			(
			){};
		}
	}
}
