// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_117__char_41__29c8d6d871e6671479d6398e0f2c53dd_Cube__char_46_SpawnTower_ea1581f7_61b8_44a4_b70b_0cc1b8ec928d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_117__char_41__29c8d6d871e6671479d6398e0f2c53dd_Cube__char_46_SpawnTower_ea1581f7_61b8_44a4_b70b_0cc1b8ec928d;

		public static void Serialize(Cube__char_32___char_40_117__char_41__29c8d6d871e6671479d6398e0f2c53dd_Cube__char_46_SpawnTower_ea1581f7_61b8_44a4_b70b_0cc1b8ec928d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_117__char_41__29c8d6d871e6671479d6398e0f2c53dd_Cube__char_46_SpawnTower_ea1581f7_61b8_44a4_b70b_0cc1b8ec928d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_117__char_41__29c8d6d871e6671479d6398e0f2c53dd_Cube__char_46_SpawnTower_ea1581f7_61b8_44a4_b70b_0cc1b8ec928d
			(
			){};
		}
	}
}
