// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_17__char_41__f8490e26e350f014692eb3bea408cfcc_Cube__char_46_SpawnTower_1546773c_ee89_4126_8156_4be04b9697c9 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_17__char_41__f8490e26e350f014692eb3bea408cfcc_Cube__char_46_SpawnTower_1546773c_ee89_4126_8156_4be04b9697c9;

		public static void Serialize(Cube__char_32___char_40_17__char_41__f8490e26e350f014692eb3bea408cfcc_Cube__char_46_SpawnTower_1546773c_ee89_4126_8156_4be04b9697c9 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_17__char_41__f8490e26e350f014692eb3bea408cfcc_Cube__char_46_SpawnTower_1546773c_ee89_4126_8156_4be04b9697c9 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_17__char_41__f8490e26e350f014692eb3bea408cfcc_Cube__char_46_SpawnTower_1546773c_ee89_4126_8156_4be04b9697c9
			(
			){};
		}
	}
}
