// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_cdfcde2c_5c27_4e11_9677_d1672d2f4d7f : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_cdfcde2c_5c27_4e11_9677_d1672d2f4d7f;

		public static void Serialize(Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_cdfcde2c_5c27_4e11_9677_d1672d2f4d7f commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_cdfcde2c_5c27_4e11_9677_d1672d2f4d7f Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_cdfcde2c_5c27_4e11_9677_d1672d2f4d7f
			(
			){};
		}
	}
}
