// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_5__char_41__7ec5c628e23d03b45a6270e28dcb369a_Cube__char_46_SpawnTower_d90fe40f_9969_46ff_a18b_e8cdbbfef374 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_5__char_41__7ec5c628e23d03b45a6270e28dcb369a_Cube__char_46_SpawnTower_d90fe40f_9969_46ff_a18b_e8cdbbfef374;

		public static void Serialize(Cube__char_32___char_40_5__char_41__7ec5c628e23d03b45a6270e28dcb369a_Cube__char_46_SpawnTower_d90fe40f_9969_46ff_a18b_e8cdbbfef374 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_5__char_41__7ec5c628e23d03b45a6270e28dcb369a_Cube__char_46_SpawnTower_d90fe40f_9969_46ff_a18b_e8cdbbfef374 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_5__char_41__7ec5c628e23d03b45a6270e28dcb369a_Cube__char_46_SpawnTower_d90fe40f_9969_46ff_a18b_e8cdbbfef374
			(
			){};
		}
	}
}
