// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_58__char_41__2849b8a7b40df234daa52f7a80b3a91b_Cube__char_46_SpawnTower_8377430d_1ee2_4414_8d6b_cb8267bb9b6b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_58__char_41__2849b8a7b40df234daa52f7a80b3a91b_Cube__char_46_SpawnTower_8377430d_1ee2_4414_8d6b_cb8267bb9b6b;

		public static void Serialize(Cube__char_32___char_40_58__char_41__2849b8a7b40df234daa52f7a80b3a91b_Cube__char_46_SpawnTower_8377430d_1ee2_4414_8d6b_cb8267bb9b6b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_58__char_41__2849b8a7b40df234daa52f7a80b3a91b_Cube__char_46_SpawnTower_8377430d_1ee2_4414_8d6b_cb8267bb9b6b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_58__char_41__2849b8a7b40df234daa52f7a80b3a91b_Cube__char_46_SpawnTower_8377430d_1ee2_4414_8d6b_cb8267bb9b6b
			(
			){};
		}
	}
}
