// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_46__char_41__f37be90d7b5390c408fb296e593c4686_Cube__char_46_SpawnTower_b832df7b_0c22_4c8b_89ed_73b37957d4b1 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_46__char_41__f37be90d7b5390c408fb296e593c4686_Cube__char_46_SpawnTower_b832df7b_0c22_4c8b_89ed_73b37957d4b1;

		public static void Serialize(Cube__char_32___char_40_46__char_41__f37be90d7b5390c408fb296e593c4686_Cube__char_46_SpawnTower_b832df7b_0c22_4c8b_89ed_73b37957d4b1 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_46__char_41__f37be90d7b5390c408fb296e593c4686_Cube__char_46_SpawnTower_b832df7b_0c22_4c8b_89ed_73b37957d4b1 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_46__char_41__f37be90d7b5390c408fb296e593c4686_Cube__char_46_SpawnTower_b832df7b_0c22_4c8b_89ed_73b37957d4b1
			(
			){};
		}
	}
}
