// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_56__char_41__854d4aec294ad2b4eb0d69d911f7adc4_Cube__char_46_SpawnTower_6298db4c_f693_4b06_95a8_6185e4ae0775 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_56__char_41__854d4aec294ad2b4eb0d69d911f7adc4_Cube__char_46_SpawnTower_6298db4c_f693_4b06_95a8_6185e4ae0775;

		public static void Serialize(Cube__char_32___char_40_56__char_41__854d4aec294ad2b4eb0d69d911f7adc4_Cube__char_46_SpawnTower_6298db4c_f693_4b06_95a8_6185e4ae0775 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_56__char_41__854d4aec294ad2b4eb0d69d911f7adc4_Cube__char_46_SpawnTower_6298db4c_f693_4b06_95a8_6185e4ae0775 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_56__char_41__854d4aec294ad2b4eb0d69d911f7adc4_Cube__char_46_SpawnTower_6298db4c_f693_4b06_95a8_6185e4ae0775
			(
			){};
		}
	}
}
