// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a : IEntityCommand
	{
		public float amount;

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a;

		public Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a
		(
			float dataamount
		)
		{
			amount = dataamount;
		}

		public static void Serialize(Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a commandData, IOutProtocolBitStream bitStream)
		{
			bitStream.WriteFloat(commandData.amount, FloatMeta.NoCompression());
		}

		public static Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a Deserialize(IInProtocolBitStream bitStream)
		{
			var dataamount = bitStream.ReadFloat(FloatMeta.NoCompression());

			return new Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_TakeDamage_fba1bdd2_68a0_43af_b2f4_3f89c88ceb4a
			(
				dataamount
			){};
		}
	}
}
