// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_48__char_41__90f995eb13b1cdd4aa81417e76a82e7c_Cube__char_46_SpawnTower_54dc6e35_56ca_4dbd_b443_22ede27409f2 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_48__char_41__90f995eb13b1cdd4aa81417e76a82e7c_Cube__char_46_SpawnTower_54dc6e35_56ca_4dbd_b443_22ede27409f2;

		public static void Serialize(Cube__char_32___char_40_48__char_41__90f995eb13b1cdd4aa81417e76a82e7c_Cube__char_46_SpawnTower_54dc6e35_56ca_4dbd_b443_22ede27409f2 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_48__char_41__90f995eb13b1cdd4aa81417e76a82e7c_Cube__char_46_SpawnTower_54dc6e35_56ca_4dbd_b443_22ede27409f2 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_48__char_41__90f995eb13b1cdd4aa81417e76a82e7c_Cube__char_46_SpawnTower_54dc6e35_56ca_4dbd_b443_22ede27409f2
			(
			){};
		}
	}
}
