// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_60__char_41__b368b8bd200bd8146802b4fa744bc1cf_Cube__char_46_SpawnTower_9acf4209_97e7_4598_9a23_140362ddd197 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_60__char_41__b368b8bd200bd8146802b4fa744bc1cf_Cube__char_46_SpawnTower_9acf4209_97e7_4598_9a23_140362ddd197;

		public static void Serialize(Cube__char_32___char_40_60__char_41__b368b8bd200bd8146802b4fa744bc1cf_Cube__char_46_SpawnTower_9acf4209_97e7_4598_9a23_140362ddd197 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_60__char_41__b368b8bd200bd8146802b4fa744bc1cf_Cube__char_46_SpawnTower_9acf4209_97e7_4598_9a23_140362ddd197 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_60__char_41__b368b8bd200bd8146802b4fa744bc1cf_Cube__char_46_SpawnTower_9acf4209_97e7_4598_9a23_140362ddd197
			(
			){};
		}
	}
}
