// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_77__char_41__78896e2d707e36f4e8e210e94a5f4eb4_Cube__char_46_SpawnTower_a1d8ce37_524e_49e0_94b5_4f0d25291913 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_77__char_41__78896e2d707e36f4e8e210e94a5f4eb4_Cube__char_46_SpawnTower_a1d8ce37_524e_49e0_94b5_4f0d25291913;

		public static void Serialize(Cube__char_32___char_40_77__char_41__78896e2d707e36f4e8e210e94a5f4eb4_Cube__char_46_SpawnTower_a1d8ce37_524e_49e0_94b5_4f0d25291913 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_77__char_41__78896e2d707e36f4e8e210e94a5f4eb4_Cube__char_46_SpawnTower_a1d8ce37_524e_49e0_94b5_4f0d25291913 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_77__char_41__78896e2d707e36f4e8e210e94a5f4eb4_Cube__char_46_SpawnTower_a1d8ce37_524e_49e0_94b5_4f0d25291913
			(
			){};
		}
	}
}
