// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_95__char_41__f730ab0b149c3bf49a253f961198bcde_Cube__char_46_SpawnTower_090298d4_4b58_4dc3_95c3_23f78dcb1f23 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_95__char_41__f730ab0b149c3bf49a253f961198bcde_Cube__char_46_SpawnTower_090298d4_4b58_4dc3_95c3_23f78dcb1f23;

		public static void Serialize(Cube__char_32___char_40_95__char_41__f730ab0b149c3bf49a253f961198bcde_Cube__char_46_SpawnTower_090298d4_4b58_4dc3_95c3_23f78dcb1f23 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_95__char_41__f730ab0b149c3bf49a253f961198bcde_Cube__char_46_SpawnTower_090298d4_4b58_4dc3_95c3_23f78dcb1f23 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_95__char_41__f730ab0b149c3bf49a253f961198bcde_Cube__char_46_SpawnTower_090298d4_4b58_4dc3_95c3_23f78dcb1f23
			(
			){};
		}
	}
}
