// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_121__char_41__d64d6fa8cfbdd314db00899b1aa1db24_Cube__char_46_SpawnTower_2f24dc65_b196_43a9_898c_b6c396971256 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_121__char_41__d64d6fa8cfbdd314db00899b1aa1db24_Cube__char_46_SpawnTower_2f24dc65_b196_43a9_898c_b6c396971256;

		public static void Serialize(Cube__char_32___char_40_121__char_41__d64d6fa8cfbdd314db00899b1aa1db24_Cube__char_46_SpawnTower_2f24dc65_b196_43a9_898c_b6c396971256 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_121__char_41__d64d6fa8cfbdd314db00899b1aa1db24_Cube__char_46_SpawnTower_2f24dc65_b196_43a9_898c_b6c396971256 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_121__char_41__d64d6fa8cfbdd314db00899b1aa1db24_Cube__char_46_SpawnTower_2f24dc65_b196_43a9_898c_b6c396971256
			(
			){};
		}
	}
}
