// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_91__char_41__9ca8ad654b62db54cb3b2ed4df513531_Cube__char_46_SpawnTower_f1365a94_9025_4ae8_8d2f_f6f383493c49 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_91__char_41__9ca8ad654b62db54cb3b2ed4df513531_Cube__char_46_SpawnTower_f1365a94_9025_4ae8_8d2f_f6f383493c49;

		public static void Serialize(Cube__char_32___char_40_91__char_41__9ca8ad654b62db54cb3b2ed4df513531_Cube__char_46_SpawnTower_f1365a94_9025_4ae8_8d2f_f6f383493c49 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_91__char_41__9ca8ad654b62db54cb3b2ed4df513531_Cube__char_46_SpawnTower_f1365a94_9025_4ae8_8d2f_f6f383493c49 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_91__char_41__9ca8ad654b62db54cb3b2ed4df513531_Cube__char_46_SpawnTower_f1365a94_9025_4ae8_8d2f_f6f383493c49
			(
			){};
		}
	}
}
