// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_96__char_41__f1b4a806346ccce469db1d39ce85668c_Cube__char_46_SpawnTower_81ec76e3_6695_4d5d_89d6_c4b811e5f110 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_96__char_41__f1b4a806346ccce469db1d39ce85668c_Cube__char_46_SpawnTower_81ec76e3_6695_4d5d_89d6_c4b811e5f110;

		public static void Serialize(Cube__char_32___char_40_96__char_41__f1b4a806346ccce469db1d39ce85668c_Cube__char_46_SpawnTower_81ec76e3_6695_4d5d_89d6_c4b811e5f110 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_96__char_41__f1b4a806346ccce469db1d39ce85668c_Cube__char_46_SpawnTower_81ec76e3_6695_4d5d_89d6_c4b811e5f110 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_96__char_41__f1b4a806346ccce469db1d39ce85668c_Cube__char_46_SpawnTower_81ec76e3_6695_4d5d_89d6_c4b811e5f110
			(
			){};
		}
	}
}
