// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_83__char_41__139a66fb293d4514c95e2ae3f2c76cd6_Cube__char_46_SpawnTower_b922367a_f9fc_4f24_8286_1baea9addd72 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_83__char_41__139a66fb293d4514c95e2ae3f2c76cd6_Cube__char_46_SpawnTower_b922367a_f9fc_4f24_8286_1baea9addd72;

		public static void Serialize(Cube__char_32___char_40_83__char_41__139a66fb293d4514c95e2ae3f2c76cd6_Cube__char_46_SpawnTower_b922367a_f9fc_4f24_8286_1baea9addd72 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_83__char_41__139a66fb293d4514c95e2ae3f2c76cd6_Cube__char_46_SpawnTower_b922367a_f9fc_4f24_8286_1baea9addd72 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_83__char_41__139a66fb293d4514c95e2ae3f2c76cd6_Cube__char_46_SpawnTower_b922367a_f9fc_4f24_8286_1baea9addd72
			(
			){};
		}
	}
}
