// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_63__char_41__45a9cd14c34da554a9016c6d4437c859_Cube__char_46_SpawnTower_295bc00a_9028_4ae9_84a0_1ecc462227b1 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_63__char_41__45a9cd14c34da554a9016c6d4437c859_Cube__char_46_SpawnTower_295bc00a_9028_4ae9_84a0_1ecc462227b1;

		public static void Serialize(Cube__char_32___char_40_63__char_41__45a9cd14c34da554a9016c6d4437c859_Cube__char_46_SpawnTower_295bc00a_9028_4ae9_84a0_1ecc462227b1 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_63__char_41__45a9cd14c34da554a9016c6d4437c859_Cube__char_46_SpawnTower_295bc00a_9028_4ae9_84a0_1ecc462227b1 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_63__char_41__45a9cd14c34da554a9016c6d4437c859_Cube__char_46_SpawnTower_295bc00a_9028_4ae9_84a0_1ecc462227b1
			(
			){};
		}
	}
}
