// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_3__char_41__b2a8fd18272a5e54c91b25f07642a987_Cube__char_46_SpawnTower_768e91a2_75a9_44e8_a29a_3a4979dfc36d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_3__char_41__b2a8fd18272a5e54c91b25f07642a987_Cube__char_46_SpawnTower_768e91a2_75a9_44e8_a29a_3a4979dfc36d;

		public static void Serialize(Cube__char_32___char_40_3__char_41__b2a8fd18272a5e54c91b25f07642a987_Cube__char_46_SpawnTower_768e91a2_75a9_44e8_a29a_3a4979dfc36d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_3__char_41__b2a8fd18272a5e54c91b25f07642a987_Cube__char_46_SpawnTower_768e91a2_75a9_44e8_a29a_3a4979dfc36d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_3__char_41__b2a8fd18272a5e54c91b25f07642a987_Cube__char_46_SpawnTower_768e91a2_75a9_44e8_a29a_3a4979dfc36d
			(
			){};
		}
	}
}
