// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_41__char_41__355ddc517d090a94892f8f09a085f715_Cube__char_46_SpawnTower_97091a1a_8218_4584_b993_e0ecef2c1b51 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_41__char_41__355ddc517d090a94892f8f09a085f715_Cube__char_46_SpawnTower_97091a1a_8218_4584_b993_e0ecef2c1b51;

		public static void Serialize(Cube__char_32___char_40_41__char_41__355ddc517d090a94892f8f09a085f715_Cube__char_46_SpawnTower_97091a1a_8218_4584_b993_e0ecef2c1b51 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_41__char_41__355ddc517d090a94892f8f09a085f715_Cube__char_46_SpawnTower_97091a1a_8218_4584_b993_e0ecef2c1b51 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_41__char_41__355ddc517d090a94892f8f09a085f715_Cube__char_46_SpawnTower_97091a1a_8218_4584_b993_e0ecef2c1b51
			(
			){};
		}
	}
}
