// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_94__char_41__bc3c05a768e8d0242a0bda9ff0336105_Cube__char_46_SpawnTower_f9b8ca94_9ce9_43b0_8121_586683f5334e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_94__char_41__bc3c05a768e8d0242a0bda9ff0336105_Cube__char_46_SpawnTower_f9b8ca94_9ce9_43b0_8121_586683f5334e;

		public static void Serialize(Cube__char_32___char_40_94__char_41__bc3c05a768e8d0242a0bda9ff0336105_Cube__char_46_SpawnTower_f9b8ca94_9ce9_43b0_8121_586683f5334e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_94__char_41__bc3c05a768e8d0242a0bda9ff0336105_Cube__char_46_SpawnTower_f9b8ca94_9ce9_43b0_8121_586683f5334e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_94__char_41__bc3c05a768e8d0242a0bda9ff0336105_Cube__char_46_SpawnTower_f9b8ca94_9ce9_43b0_8121_586683f5334e
			(
			){};
		}
	}
}
