// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_24__char_41__e2caab4e4703dea4f9a36c1562e4046e_Cube__char_46_SpawnTower_c18151c6_337d_45c6_8f68_7222b26e5064 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_24__char_41__e2caab4e4703dea4f9a36c1562e4046e_Cube__char_46_SpawnTower_c18151c6_337d_45c6_8f68_7222b26e5064;

		public static void Serialize(Cube__char_32___char_40_24__char_41__e2caab4e4703dea4f9a36c1562e4046e_Cube__char_46_SpawnTower_c18151c6_337d_45c6_8f68_7222b26e5064 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_24__char_41__e2caab4e4703dea4f9a36c1562e4046e_Cube__char_46_SpawnTower_c18151c6_337d_45c6_8f68_7222b26e5064 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_24__char_41__e2caab4e4703dea4f9a36c1562e4046e_Cube__char_46_SpawnTower_c18151c6_337d_45c6_8f68_7222b26e5064
			(
			){};
		}
	}
}
