// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_8__char_41__b127b4d2ca09872478c7d2e0bd4569a9_Cube__char_46_SpawnTower_3d6a4fad_e49d_4378_bd71_7f637b480203 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_8__char_41__b127b4d2ca09872478c7d2e0bd4569a9_Cube__char_46_SpawnTower_3d6a4fad_e49d_4378_bd71_7f637b480203;

		public static void Serialize(Cube__char_32___char_40_8__char_41__b127b4d2ca09872478c7d2e0bd4569a9_Cube__char_46_SpawnTower_3d6a4fad_e49d_4378_bd71_7f637b480203 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_8__char_41__b127b4d2ca09872478c7d2e0bd4569a9_Cube__char_46_SpawnTower_3d6a4fad_e49d_4378_bd71_7f637b480203 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_8__char_41__b127b4d2ca09872478c7d2e0bd4569a9_Cube__char_46_SpawnTower_3d6a4fad_e49d_4378_bd71_7f637b480203
			(
			){};
		}
	}
}
