// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_61__char_41__250d9f4836ece6f44b723ca530f36ab6_Cube__char_46_SpawnTower_d0dc7c13_fa0c_49ef_9495_6c23c2f97a26 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_61__char_41__250d9f4836ece6f44b723ca530f36ab6_Cube__char_46_SpawnTower_d0dc7c13_fa0c_49ef_9495_6c23c2f97a26;

		public static void Serialize(Cube__char_32___char_40_61__char_41__250d9f4836ece6f44b723ca530f36ab6_Cube__char_46_SpawnTower_d0dc7c13_fa0c_49ef_9495_6c23c2f97a26 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_61__char_41__250d9f4836ece6f44b723ca530f36ab6_Cube__char_46_SpawnTower_d0dc7c13_fa0c_49ef_9495_6c23c2f97a26 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_61__char_41__250d9f4836ece6f44b723ca530f36ab6_Cube__char_46_SpawnTower_d0dc7c13_fa0c_49ef_9495_6c23c2f97a26
			(
			){};
		}
	}
}
