// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_113__char_41__7f3dc5e1460c94e48be3a8cdca97d5e6_Cube__char_46_SpawnTower_091aa0b3_7799_4b78_a2f9_ce8167c40930 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_113__char_41__7f3dc5e1460c94e48be3a8cdca97d5e6_Cube__char_46_SpawnTower_091aa0b3_7799_4b78_a2f9_ce8167c40930;

		public static void Serialize(Cube__char_32___char_40_113__char_41__7f3dc5e1460c94e48be3a8cdca97d5e6_Cube__char_46_SpawnTower_091aa0b3_7799_4b78_a2f9_ce8167c40930 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_113__char_41__7f3dc5e1460c94e48be3a8cdca97d5e6_Cube__char_46_SpawnTower_091aa0b3_7799_4b78_a2f9_ce8167c40930 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_113__char_41__7f3dc5e1460c94e48be3a8cdca97d5e6_Cube__char_46_SpawnTower_091aa0b3_7799_4b78_a2f9_ce8167c40930
			(
			){};
		}
	}
}
