// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_112__char_41__d1c46efa9b34b6e41b8c810bf7fc4712_Cube__char_46_SpawnTower_3d573c7d_0dc2_49b9_88b3_cf08db363fbf : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_112__char_41__d1c46efa9b34b6e41b8c810bf7fc4712_Cube__char_46_SpawnTower_3d573c7d_0dc2_49b9_88b3_cf08db363fbf;

		public static void Serialize(Cube__char_32___char_40_112__char_41__d1c46efa9b34b6e41b8c810bf7fc4712_Cube__char_46_SpawnTower_3d573c7d_0dc2_49b9_88b3_cf08db363fbf commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_112__char_41__d1c46efa9b34b6e41b8c810bf7fc4712_Cube__char_46_SpawnTower_3d573c7d_0dc2_49b9_88b3_cf08db363fbf Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_112__char_41__d1c46efa9b34b6e41b8c810bf7fc4712_Cube__char_46_SpawnTower_3d573c7d_0dc2_49b9_88b3_cf08db363fbf
			(
			){};
		}
	}
}
