// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_21__char_41__0004cc851fc4129419935595504ee236_Cube__char_46_SpawnTower_cdd19975_1917_466e_969b_a51ec92efd13 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_21__char_41__0004cc851fc4129419935595504ee236_Cube__char_46_SpawnTower_cdd19975_1917_466e_969b_a51ec92efd13;

		public static void Serialize(Cube__char_32___char_40_21__char_41__0004cc851fc4129419935595504ee236_Cube__char_46_SpawnTower_cdd19975_1917_466e_969b_a51ec92efd13 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_21__char_41__0004cc851fc4129419935595504ee236_Cube__char_46_SpawnTower_cdd19975_1917_466e_969b_a51ec92efd13 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_21__char_41__0004cc851fc4129419935595504ee236_Cube__char_46_SpawnTower_cdd19975_1917_466e_969b_a51ec92efd13
			(
			){};
		}
	}
}
