// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_25__char_41__7b4449a5497e93d46ac75b591d6ccebb_Cube__char_46_SpawnTower_ffd19a67_bb12_47a8_af35_d7e19292ff43 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_25__char_41__7b4449a5497e93d46ac75b591d6ccebb_Cube__char_46_SpawnTower_ffd19a67_bb12_47a8_af35_d7e19292ff43;

		public static void Serialize(Cube__char_32___char_40_25__char_41__7b4449a5497e93d46ac75b591d6ccebb_Cube__char_46_SpawnTower_ffd19a67_bb12_47a8_af35_d7e19292ff43 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_25__char_41__7b4449a5497e93d46ac75b591d6ccebb_Cube__char_46_SpawnTower_ffd19a67_bb12_47a8_af35_d7e19292ff43 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_25__char_41__7b4449a5497e93d46ac75b591d6ccebb_Cube__char_46_SpawnTower_ffd19a67_bb12_47a8_af35_d7e19292ff43
			(
			){};
		}
	}
}
