// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_68__char_41__2b092b4e7603c344686446b73cd559f1_Cube__char_46_SpawnTower_eb213d3e_bdb1_4c45_896f_a0e1b815a63c : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_68__char_41__2b092b4e7603c344686446b73cd559f1_Cube__char_46_SpawnTower_eb213d3e_bdb1_4c45_896f_a0e1b815a63c;

		public static void Serialize(Cube__char_32___char_40_68__char_41__2b092b4e7603c344686446b73cd559f1_Cube__char_46_SpawnTower_eb213d3e_bdb1_4c45_896f_a0e1b815a63c commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_68__char_41__2b092b4e7603c344686446b73cd559f1_Cube__char_46_SpawnTower_eb213d3e_bdb1_4c45_896f_a0e1b815a63c Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_68__char_41__2b092b4e7603c344686446b73cd559f1_Cube__char_46_SpawnTower_eb213d3e_bdb1_4c45_896f_a0e1b815a63c
			(
			){};
		}
	}
}
