// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_67__char_41__b4f61696fb47f1d49af583bea4d24874_Cube__char_46_SpawnTower_b5fce475_4e86_418b_b8de_843b927bc995 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_67__char_41__b4f61696fb47f1d49af583bea4d24874_Cube__char_46_SpawnTower_b5fce475_4e86_418b_b8de_843b927bc995;

		public static void Serialize(Cube__char_32___char_40_67__char_41__b4f61696fb47f1d49af583bea4d24874_Cube__char_46_SpawnTower_b5fce475_4e86_418b_b8de_843b927bc995 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_67__char_41__b4f61696fb47f1d49af583bea4d24874_Cube__char_46_SpawnTower_b5fce475_4e86_418b_b8de_843b927bc995 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_67__char_41__b4f61696fb47f1d49af583bea4d24874_Cube__char_46_SpawnTower_b5fce475_4e86_418b_b8de_843b927bc995
			(
			){};
		}
	}
}
