// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_78__char_41__07d3064fdc6cc454bb871c9c01563a61_Cube__char_46_SpawnTower_025eb746_02fa_496a_9d87_57fb8e5d101d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_78__char_41__07d3064fdc6cc454bb871c9c01563a61_Cube__char_46_SpawnTower_025eb746_02fa_496a_9d87_57fb8e5d101d;

		public static void Serialize(Cube__char_32___char_40_78__char_41__07d3064fdc6cc454bb871c9c01563a61_Cube__char_46_SpawnTower_025eb746_02fa_496a_9d87_57fb8e5d101d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_78__char_41__07d3064fdc6cc454bb871c9c01563a61_Cube__char_46_SpawnTower_025eb746_02fa_496a_9d87_57fb8e5d101d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_78__char_41__07d3064fdc6cc454bb871c9c01563a61_Cube__char_46_SpawnTower_025eb746_02fa_496a_9d87_57fb8e5d101d
			(
			){};
		}
	}
}
