// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_11__char_41__8882713c0e1211847add5d0cf258e578_Cube__char_46_SpawnTower_2323be48_9104_467e_be72_bcd20cf04cd7 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_11__char_41__8882713c0e1211847add5d0cf258e578_Cube__char_46_SpawnTower_2323be48_9104_467e_be72_bcd20cf04cd7;

		public static void Serialize(Cube__char_32___char_40_11__char_41__8882713c0e1211847add5d0cf258e578_Cube__char_46_SpawnTower_2323be48_9104_467e_be72_bcd20cf04cd7 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_11__char_41__8882713c0e1211847add5d0cf258e578_Cube__char_46_SpawnTower_2323be48_9104_467e_be72_bcd20cf04cd7 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_11__char_41__8882713c0e1211847add5d0cf258e578_Cube__char_46_SpawnTower_2323be48_9104_467e_be72_bcd20cf04cd7
			(
			){};
		}
	}
}
