// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_57__char_41__fbbb93d1afc9c484192a59a05067d4ae_Cube__char_46_SpawnTower_750acde7_0b4d_486d_a50f_11384ce7d6d3 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_57__char_41__fbbb93d1afc9c484192a59a05067d4ae_Cube__char_46_SpawnTower_750acde7_0b4d_486d_a50f_11384ce7d6d3;

		public static void Serialize(Cube__char_32___char_40_57__char_41__fbbb93d1afc9c484192a59a05067d4ae_Cube__char_46_SpawnTower_750acde7_0b4d_486d_a50f_11384ce7d6d3 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_57__char_41__fbbb93d1afc9c484192a59a05067d4ae_Cube__char_46_SpawnTower_750acde7_0b4d_486d_a50f_11384ce7d6d3 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_57__char_41__fbbb93d1afc9c484192a59a05067d4ae_Cube__char_46_SpawnTower_750acde7_0b4d_486d_a50f_11384ce7d6d3
			(
			){};
		}
	}
}
