// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_108__char_41__926e377d05d174b4590bb9610f0f3806_Cube__char_46_SpawnTower_9712aad2_ac49_4efd_950b_53f3061733fe : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_108__char_41__926e377d05d174b4590bb9610f0f3806_Cube__char_46_SpawnTower_9712aad2_ac49_4efd_950b_53f3061733fe;

		public static void Serialize(Cube__char_32___char_40_108__char_41__926e377d05d174b4590bb9610f0f3806_Cube__char_46_SpawnTower_9712aad2_ac49_4efd_950b_53f3061733fe commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_108__char_41__926e377d05d174b4590bb9610f0f3806_Cube__char_46_SpawnTower_9712aad2_ac49_4efd_950b_53f3061733fe Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_108__char_41__926e377d05d174b4590bb9610f0f3806_Cube__char_46_SpawnTower_9712aad2_ac49_4efd_950b_53f3061733fe
			(
			){};
		}
	}
}
