// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_66__char_41__b6326d318974e1d40925a50a9bd01e3a_Cube__char_46_SpawnTower_af321694_6487_4873_9eba_e5f30bf36c60 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_66__char_41__b6326d318974e1d40925a50a9bd01e3a_Cube__char_46_SpawnTower_af321694_6487_4873_9eba_e5f30bf36c60;

		public static void Serialize(Cube__char_32___char_40_66__char_41__b6326d318974e1d40925a50a9bd01e3a_Cube__char_46_SpawnTower_af321694_6487_4873_9eba_e5f30bf36c60 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_66__char_41__b6326d318974e1d40925a50a9bd01e3a_Cube__char_46_SpawnTower_af321694_6487_4873_9eba_e5f30bf36c60 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_66__char_41__b6326d318974e1d40925a50a9bd01e3a_Cube__char_46_SpawnTower_af321694_6487_4873_9eba_e5f30bf36c60
			(
			){};
		}
	}
}
