// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_10__char_41__98ba8590ba9a6224f887f021f2cd2f43_Cube__char_46_SpawnTower_bb4fd31c_09c4_48bc_b28f_11c30ecbcf04 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_10__char_41__98ba8590ba9a6224f887f021f2cd2f43_Cube__char_46_SpawnTower_bb4fd31c_09c4_48bc_b28f_11c30ecbcf04;

		public static void Serialize(Cube__char_32___char_40_10__char_41__98ba8590ba9a6224f887f021f2cd2f43_Cube__char_46_SpawnTower_bb4fd31c_09c4_48bc_b28f_11c30ecbcf04 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_10__char_41__98ba8590ba9a6224f887f021f2cd2f43_Cube__char_46_SpawnTower_bb4fd31c_09c4_48bc_b28f_11c30ecbcf04 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_10__char_41__98ba8590ba9a6224f887f021f2cd2f43_Cube__char_46_SpawnTower_bb4fd31c_09c4_48bc_b28f_11c30ecbcf04
			(
			){};
		}
	}
}
