// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_110__char_41__2a0470751b88ced44bf82d9a02dbb93c_Cube__char_46_SpawnTower_511051c1_cdec_4c4a_b44f_efa9aa260940 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_110__char_41__2a0470751b88ced44bf82d9a02dbb93c_Cube__char_46_SpawnTower_511051c1_cdec_4c4a_b44f_efa9aa260940;

		public static void Serialize(Cube__char_32___char_40_110__char_41__2a0470751b88ced44bf82d9a02dbb93c_Cube__char_46_SpawnTower_511051c1_cdec_4c4a_b44f_efa9aa260940 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_110__char_41__2a0470751b88ced44bf82d9a02dbb93c_Cube__char_46_SpawnTower_511051c1_cdec_4c4a_b44f_efa9aa260940 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_110__char_41__2a0470751b88ced44bf82d9a02dbb93c_Cube__char_46_SpawnTower_511051c1_cdec_4c4a_b44f_efa9aa260940
			(
			){};
		}
	}
}
