// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_26__char_41__2470d16795d2e1247b07455f9fadcdfe_Cube__char_46_SpawnTower_247c4c51_2a26_4296_af4e_febf3a23c3bb : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_26__char_41__2470d16795d2e1247b07455f9fadcdfe_Cube__char_46_SpawnTower_247c4c51_2a26_4296_af4e_febf3a23c3bb;

		public static void Serialize(Cube__char_32___char_40_26__char_41__2470d16795d2e1247b07455f9fadcdfe_Cube__char_46_SpawnTower_247c4c51_2a26_4296_af4e_febf3a23c3bb commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_26__char_41__2470d16795d2e1247b07455f9fadcdfe_Cube__char_46_SpawnTower_247c4c51_2a26_4296_af4e_febf3a23c3bb Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_26__char_41__2470d16795d2e1247b07455f9fadcdfe_Cube__char_46_SpawnTower_247c4c51_2a26_4296_af4e_febf3a23c3bb
			(
			){};
		}
	}
}
