// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_64__char_41__7efce74a6413cee42b6cda94bd641b6e_Cube__char_46_SpawnTower_1ed8c0db_e6ba_4df0_8f60_c5b6a71636b1 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_64__char_41__7efce74a6413cee42b6cda94bd641b6e_Cube__char_46_SpawnTower_1ed8c0db_e6ba_4df0_8f60_c5b6a71636b1;

		public static void Serialize(Cube__char_32___char_40_64__char_41__7efce74a6413cee42b6cda94bd641b6e_Cube__char_46_SpawnTower_1ed8c0db_e6ba_4df0_8f60_c5b6a71636b1 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_64__char_41__7efce74a6413cee42b6cda94bd641b6e_Cube__char_46_SpawnTower_1ed8c0db_e6ba_4df0_8f60_c5b6a71636b1 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_64__char_41__7efce74a6413cee42b6cda94bd641b6e_Cube__char_46_SpawnTower_1ed8c0db_e6ba_4df0_8f60_c5b6a71636b1
			(
			){};
		}
	}
}
