// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_84__char_41__b642027f3cdb34041989a5478bf23358_Cube__char_46_SpawnTower_7a2bb8dc_f214_434d_8123_7c13979c1499 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_84__char_41__b642027f3cdb34041989a5478bf23358_Cube__char_46_SpawnTower_7a2bb8dc_f214_434d_8123_7c13979c1499;

		public static void Serialize(Cube__char_32___char_40_84__char_41__b642027f3cdb34041989a5478bf23358_Cube__char_46_SpawnTower_7a2bb8dc_f214_434d_8123_7c13979c1499 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_84__char_41__b642027f3cdb34041989a5478bf23358_Cube__char_46_SpawnTower_7a2bb8dc_f214_434d_8123_7c13979c1499 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_84__char_41__b642027f3cdb34041989a5478bf23358_Cube__char_46_SpawnTower_7a2bb8dc_f214_434d_8123_7c13979c1499
			(
			){};
		}
	}
}
