// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_42__char_41__d3b177559e3e0514dab3fe83c022142c_Cube__char_46_SpawnTower_6385d070_0b29_4a7e_a5b6_9207d7b38371 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_42__char_41__d3b177559e3e0514dab3fe83c022142c_Cube__char_46_SpawnTower_6385d070_0b29_4a7e_a5b6_9207d7b38371;

		public static void Serialize(Cube__char_32___char_40_42__char_41__d3b177559e3e0514dab3fe83c022142c_Cube__char_46_SpawnTower_6385d070_0b29_4a7e_a5b6_9207d7b38371 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_42__char_41__d3b177559e3e0514dab3fe83c022142c_Cube__char_46_SpawnTower_6385d070_0b29_4a7e_a5b6_9207d7b38371 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_42__char_41__d3b177559e3e0514dab3fe83c022142c_Cube__char_46_SpawnTower_6385d070_0b29_4a7e_a5b6_9207d7b38371
			(
			){};
		}
	}
}
