// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_45__char_41__286f82165efb5334db90e668c47cf24a_Cube__char_46_SpawnTower_15391fc2_9f29_477d_a7eb_b6854993f100 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_45__char_41__286f82165efb5334db90e668c47cf24a_Cube__char_46_SpawnTower_15391fc2_9f29_477d_a7eb_b6854993f100;

		public static void Serialize(Cube__char_32___char_40_45__char_41__286f82165efb5334db90e668c47cf24a_Cube__char_46_SpawnTower_15391fc2_9f29_477d_a7eb_b6854993f100 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_45__char_41__286f82165efb5334db90e668c47cf24a_Cube__char_46_SpawnTower_15391fc2_9f29_477d_a7eb_b6854993f100 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_45__char_41__286f82165efb5334db90e668c47cf24a_Cube__char_46_SpawnTower_15391fc2_9f29_477d_a7eb_b6854993f100
			(
			){};
		}
	}
}
