// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_30__char_41__2f12ed925991606438318257168b5ae5_Cube__char_46_SpawnTower_5c4f8b40_d1a4_422c_98af_473b5c4b2e85 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_30__char_41__2f12ed925991606438318257168b5ae5_Cube__char_46_SpawnTower_5c4f8b40_d1a4_422c_98af_473b5c4b2e85;

		public static void Serialize(Cube__char_32___char_40_30__char_41__2f12ed925991606438318257168b5ae5_Cube__char_46_SpawnTower_5c4f8b40_d1a4_422c_98af_473b5c4b2e85 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_30__char_41__2f12ed925991606438318257168b5ae5_Cube__char_46_SpawnTower_5c4f8b40_d1a4_422c_98af_473b5c4b2e85 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_30__char_41__2f12ed925991606438318257168b5ae5_Cube__char_46_SpawnTower_5c4f8b40_d1a4_422c_98af_473b5c4b2e85
			(
			){};
		}
	}
}
