// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_16__char_41__d788cfd4c0e789e45a42ea3feb919e12_Cube__char_46_SpawnTower_c4b76ead_3750_4045_a1d2_e2e10e8bb0be : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_16__char_41__d788cfd4c0e789e45a42ea3feb919e12_Cube__char_46_SpawnTower_c4b76ead_3750_4045_a1d2_e2e10e8bb0be;

		public static void Serialize(Cube__char_32___char_40_16__char_41__d788cfd4c0e789e45a42ea3feb919e12_Cube__char_46_SpawnTower_c4b76ead_3750_4045_a1d2_e2e10e8bb0be commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_16__char_41__d788cfd4c0e789e45a42ea3feb919e12_Cube__char_46_SpawnTower_c4b76ead_3750_4045_a1d2_e2e10e8bb0be Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_16__char_41__d788cfd4c0e789e45a42ea3feb919e12_Cube__char_46_SpawnTower_c4b76ead_3750_4045_a1d2_e2e10e8bb0be
			(
			){};
		}
	}
}
