// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_39__char_41__509d98c3b6ce4a745bbea1e0bfebfc98_Cube__char_46_SpawnTower_a198dbd3_90c2_4896_b546_fb2bfc1d5f2a : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_39__char_41__509d98c3b6ce4a745bbea1e0bfebfc98_Cube__char_46_SpawnTower_a198dbd3_90c2_4896_b546_fb2bfc1d5f2a;

		public static void Serialize(Cube__char_32___char_40_39__char_41__509d98c3b6ce4a745bbea1e0bfebfc98_Cube__char_46_SpawnTower_a198dbd3_90c2_4896_b546_fb2bfc1d5f2a commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_39__char_41__509d98c3b6ce4a745bbea1e0bfebfc98_Cube__char_46_SpawnTower_a198dbd3_90c2_4896_b546_fb2bfc1d5f2a Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_39__char_41__509d98c3b6ce4a745bbea1e0bfebfc98_Cube__char_46_SpawnTower_a198dbd3_90c2_4896_b546_fb2bfc1d5f2a
			(
			){};
		}
	}
}
