// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_101__char_41__7e11d667309ccf7439a9a6dd09116b9e_Cube__char_46_SpawnTower_5e7f0765_5139_4934_a441_8cb42fa8738c : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_101__char_41__7e11d667309ccf7439a9a6dd09116b9e_Cube__char_46_SpawnTower_5e7f0765_5139_4934_a441_8cb42fa8738c;

		public static void Serialize(Cube__char_32___char_40_101__char_41__7e11d667309ccf7439a9a6dd09116b9e_Cube__char_46_SpawnTower_5e7f0765_5139_4934_a441_8cb42fa8738c commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_101__char_41__7e11d667309ccf7439a9a6dd09116b9e_Cube__char_46_SpawnTower_5e7f0765_5139_4934_a441_8cb42fa8738c Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_101__char_41__7e11d667309ccf7439a9a6dd09116b9e_Cube__char_46_SpawnTower_5e7f0765_5139_4934_a441_8cb42fa8738c
			(
			){};
		}
	}
}
