// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_81__char_41__04434397eff8d8f4da077ef2a12a311a_Cube__char_46_SpawnTower_faa9cf4e_4724_46ce_948c_b7688e02cb75 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_81__char_41__04434397eff8d8f4da077ef2a12a311a_Cube__char_46_SpawnTower_faa9cf4e_4724_46ce_948c_b7688e02cb75;

		public static void Serialize(Cube__char_32___char_40_81__char_41__04434397eff8d8f4da077ef2a12a311a_Cube__char_46_SpawnTower_faa9cf4e_4724_46ce_948c_b7688e02cb75 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_81__char_41__04434397eff8d8f4da077ef2a12a311a_Cube__char_46_SpawnTower_faa9cf4e_4724_46ce_948c_b7688e02cb75 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_81__char_41__04434397eff8d8f4da077ef2a12a311a_Cube__char_46_SpawnTower_faa9cf4e_4724_46ce_948c_b7688e02cb75
			(
			){};
		}
	}
}
