// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_59__char_41__e04c5c57328c9804a9143a3527116229_Cube__char_46_SpawnTower_37ce2e09_77db_474e_b893_dc11a0f89e9d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_59__char_41__e04c5c57328c9804a9143a3527116229_Cube__char_46_SpawnTower_37ce2e09_77db_474e_b893_dc11a0f89e9d;

		public static void Serialize(Cube__char_32___char_40_59__char_41__e04c5c57328c9804a9143a3527116229_Cube__char_46_SpawnTower_37ce2e09_77db_474e_b893_dc11a0f89e9d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_59__char_41__e04c5c57328c9804a9143a3527116229_Cube__char_46_SpawnTower_37ce2e09_77db_474e_b893_dc11a0f89e9d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_59__char_41__e04c5c57328c9804a9143a3527116229_Cube__char_46_SpawnTower_37ce2e09_77db_474e_b893_dc11a0f89e9d
			(
			){};
		}
	}
}
