// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_19__char_41__d48911e1abb7eff4985521991568f993_Cube__char_46_SpawnTower_3951c758_38c5_462c_9608_8a3fa6924dc7 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_19__char_41__d48911e1abb7eff4985521991568f993_Cube__char_46_SpawnTower_3951c758_38c5_462c_9608_8a3fa6924dc7;

		public static void Serialize(Cube__char_32___char_40_19__char_41__d48911e1abb7eff4985521991568f993_Cube__char_46_SpawnTower_3951c758_38c5_462c_9608_8a3fa6924dc7 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_19__char_41__d48911e1abb7eff4985521991568f993_Cube__char_46_SpawnTower_3951c758_38c5_462c_9608_8a3fa6924dc7 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_19__char_41__d48911e1abb7eff4985521991568f993_Cube__char_46_SpawnTower_3951c758_38c5_462c_9608_8a3fa6924dc7
			(
			){};
		}
	}
}
