// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_122__char_41__96d1dd22d5f0c894c95da2b102bb66a6_Cube__char_46_SpawnTower_8d8f72c1_7ac2_4cd0_9ef6_5b75445dfe4b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_122__char_41__96d1dd22d5f0c894c95da2b102bb66a6_Cube__char_46_SpawnTower_8d8f72c1_7ac2_4cd0_9ef6_5b75445dfe4b;

		public static void Serialize(Cube__char_32___char_40_122__char_41__96d1dd22d5f0c894c95da2b102bb66a6_Cube__char_46_SpawnTower_8d8f72c1_7ac2_4cd0_9ef6_5b75445dfe4b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_122__char_41__96d1dd22d5f0c894c95da2b102bb66a6_Cube__char_46_SpawnTower_8d8f72c1_7ac2_4cd0_9ef6_5b75445dfe4b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_122__char_41__96d1dd22d5f0c894c95da2b102bb66a6_Cube__char_46_SpawnTower_8d8f72c1_7ac2_4cd0_9ef6_5b75445dfe4b
			(
			){};
		}
	}
}
