// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_6__char_41__8c07c56c976b83a4490f15e0d96924f0_Cube__char_46_SpawnTower_9487debb_6ceb_4cea_9508_7c413b2cea99 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_6__char_41__8c07c56c976b83a4490f15e0d96924f0_Cube__char_46_SpawnTower_9487debb_6ceb_4cea_9508_7c413b2cea99;

		public static void Serialize(Cube__char_32___char_40_6__char_41__8c07c56c976b83a4490f15e0d96924f0_Cube__char_46_SpawnTower_9487debb_6ceb_4cea_9508_7c413b2cea99 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_6__char_41__8c07c56c976b83a4490f15e0d96924f0_Cube__char_46_SpawnTower_9487debb_6ceb_4cea_9508_7c413b2cea99 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_6__char_41__8c07c56c976b83a4490f15e0d96924f0_Cube__char_46_SpawnTower_9487debb_6ceb_4cea_9508_7c413b2cea99
			(
			){};
		}
	}
}
