// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_9__char_41__11b2ef88beefb1c48abfd77661abe412_Cube__char_46_SpawnTower_21048834_adcf_431f_afd5_acd3515d86ec : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_9__char_41__11b2ef88beefb1c48abfd77661abe412_Cube__char_46_SpawnTower_21048834_adcf_431f_afd5_acd3515d86ec;

		public static void Serialize(Cube__char_32___char_40_9__char_41__11b2ef88beefb1c48abfd77661abe412_Cube__char_46_SpawnTower_21048834_adcf_431f_afd5_acd3515d86ec commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_9__char_41__11b2ef88beefb1c48abfd77661abe412_Cube__char_46_SpawnTower_21048834_adcf_431f_afd5_acd3515d86ec Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_9__char_41__11b2ef88beefb1c48abfd77661abe412_Cube__char_46_SpawnTower_21048834_adcf_431f_afd5_acd3515d86ec
			(
			){};
		}
	}
}
