// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_79__char_41__90ba63065aff19847af265863d4840e8_Cube__char_46_SpawnTower_439d07df_5204_46db_be5b_6d34fc975b9a : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_79__char_41__90ba63065aff19847af265863d4840e8_Cube__char_46_SpawnTower_439d07df_5204_46db_be5b_6d34fc975b9a;

		public static void Serialize(Cube__char_32___char_40_79__char_41__90ba63065aff19847af265863d4840e8_Cube__char_46_SpawnTower_439d07df_5204_46db_be5b_6d34fc975b9a commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_79__char_41__90ba63065aff19847af265863d4840e8_Cube__char_46_SpawnTower_439d07df_5204_46db_be5b_6d34fc975b9a Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_79__char_41__90ba63065aff19847af265863d4840e8_Cube__char_46_SpawnTower_439d07df_5204_46db_be5b_6d34fc975b9a
			(
			){};
		}
	}
}
