// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_102__char_41__d3caaf60927fe494e82ad68f7c720d50_Cube__char_46_SpawnTower_eac3055c_cdcb_4f9a_8de8_a5a69fb9904b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_102__char_41__d3caaf60927fe494e82ad68f7c720d50_Cube__char_46_SpawnTower_eac3055c_cdcb_4f9a_8de8_a5a69fb9904b;

		public static void Serialize(Cube__char_32___char_40_102__char_41__d3caaf60927fe494e82ad68f7c720d50_Cube__char_46_SpawnTower_eac3055c_cdcb_4f9a_8de8_a5a69fb9904b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_102__char_41__d3caaf60927fe494e82ad68f7c720d50_Cube__char_46_SpawnTower_eac3055c_cdcb_4f9a_8de8_a5a69fb9904b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_102__char_41__d3caaf60927fe494e82ad68f7c720d50_Cube__char_46_SpawnTower_eac3055c_cdcb_4f9a_8de8_a5a69fb9904b
			(
			){};
		}
	}
}
