// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_82__char_41__a05a484bd44312a4180dadd6546bf46a_Cube__char_46_SpawnTower_ef553197_d621_434c_a77c_cbace1f990ff : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_82__char_41__a05a484bd44312a4180dadd6546bf46a_Cube__char_46_SpawnTower_ef553197_d621_434c_a77c_cbace1f990ff;

		public static void Serialize(Cube__char_32___char_40_82__char_41__a05a484bd44312a4180dadd6546bf46a_Cube__char_46_SpawnTower_ef553197_d621_434c_a77c_cbace1f990ff commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_82__char_41__a05a484bd44312a4180dadd6546bf46a_Cube__char_46_SpawnTower_ef553197_d621_434c_a77c_cbace1f990ff Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_82__char_41__a05a484bd44312a4180dadd6546bf46a_Cube__char_46_SpawnTower_ef553197_d621_434c_a77c_cbace1f990ff
			(
			){};
		}
	}
}
