// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_38__char_41__171468e5ea4e7ec44a95b86871f06d41_Cube__char_46_SpawnTower_4a5548f7_e512_445b_8617_2df18609c765 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_38__char_41__171468e5ea4e7ec44a95b86871f06d41_Cube__char_46_SpawnTower_4a5548f7_e512_445b_8617_2df18609c765;

		public static void Serialize(Cube__char_32___char_40_38__char_41__171468e5ea4e7ec44a95b86871f06d41_Cube__char_46_SpawnTower_4a5548f7_e512_445b_8617_2df18609c765 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_38__char_41__171468e5ea4e7ec44a95b86871f06d41_Cube__char_46_SpawnTower_4a5548f7_e512_445b_8617_2df18609c765 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_38__char_41__171468e5ea4e7ec44a95b86871f06d41_Cube__char_46_SpawnTower_4a5548f7_e512_445b_8617_2df18609c765
			(
			){};
		}
	}
}
