// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_18__char_41__cf956191440249047b34ad3e94abe854_Cube__char_46_NonHover_b40a91d1_bb2d_47e0_a792_5a2a43c88d29 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_18__char_41__cf956191440249047b34ad3e94abe854_Cube__char_46_NonHover_b40a91d1_bb2d_47e0_a792_5a2a43c88d29;

		public static void Serialize(Cube__char_32___char_40_18__char_41__cf956191440249047b34ad3e94abe854_Cube__char_46_NonHover_b40a91d1_bb2d_47e0_a792_5a2a43c88d29 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_18__char_41__cf956191440249047b34ad3e94abe854_Cube__char_46_NonHover_b40a91d1_bb2d_47e0_a792_5a2a43c88d29 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_18__char_41__cf956191440249047b34ad3e94abe854_Cube__char_46_NonHover_b40a91d1_bb2d_47e0_a792_5a2a43c88d29
			(
			){};
		}
	}
}
