// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861 : ICoherenceComponentData
	{
		public float health;

		public override string ToString()
		{
			return $"Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861(health: {health})";
		}

		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861;

		public const int order = 0;

		public uint FieldsMask => 0b00000000000000000000000000000001;

		public int GetComponentOrder() => order;
		public bool IsSendOrdered() { return false; }

		public AbsoluteSimulationFrame Frame;
	

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				health = other.health;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static uint Serialize(Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				var fieldValue = data.health;

				bitStream.WriteFloat(fieldValue, FloatMeta.NoCompression());
			}
			mask >>= 1;

			return mask;
		}

		public static (Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861();
	
			if (bitStream.ReadMask())
			{
				val.health = bitStream.ReadFloat(FloatMeta.NoCompression());
				mask |= 0b00000000000000000000000000000001;
			}
			return (val, mask);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health_1468250657583452861?;
	
		}
	}
}