// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_34__char_41__32af914b983208e4e8bf9705e2b84921_Cube__char_46_SpawnTower_62505d0f_4e43_4293_87a0_a4be59f06b83 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_34__char_41__32af914b983208e4e8bf9705e2b84921_Cube__char_46_SpawnTower_62505d0f_4e43_4293_87a0_a4be59f06b83;

		public static void Serialize(Cube__char_32___char_40_34__char_41__32af914b983208e4e8bf9705e2b84921_Cube__char_46_SpawnTower_62505d0f_4e43_4293_87a0_a4be59f06b83 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_34__char_41__32af914b983208e4e8bf9705e2b84921_Cube__char_46_SpawnTower_62505d0f_4e43_4293_87a0_a4be59f06b83 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_34__char_41__32af914b983208e4e8bf9705e2b84921_Cube__char_46_SpawnTower_62505d0f_4e43_4293_87a0_a4be59f06b83
			(
			){};
		}
	}
}
