// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_49__char_41__bef88510ed7b7f5419fd800a2e017cd4_Cube__char_46_SpawnTower_e11db5d5_2390_48d8_8543_d98d1bc70d53 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_49__char_41__bef88510ed7b7f5419fd800a2e017cd4_Cube__char_46_SpawnTower_e11db5d5_2390_48d8_8543_d98d1bc70d53;

		public static void Serialize(Cube__char_32___char_40_49__char_41__bef88510ed7b7f5419fd800a2e017cd4_Cube__char_46_SpawnTower_e11db5d5_2390_48d8_8543_d98d1bc70d53 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_49__char_41__bef88510ed7b7f5419fd800a2e017cd4_Cube__char_46_SpawnTower_e11db5d5_2390_48d8_8543_d98d1bc70d53 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_49__char_41__bef88510ed7b7f5419fd800a2e017cd4_Cube__char_46_SpawnTower_e11db5d5_2390_48d8_8543_d98d1bc70d53
			(
			){};
		}
	}
}
