// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_37__char_41__61eafb88fd9d6194ba45b87da05ebf7d_Cube__char_46_SpawnTower_daa5cd4f_fdab_4c45_a328_e468bc320a3f : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_37__char_41__61eafb88fd9d6194ba45b87da05ebf7d_Cube__char_46_SpawnTower_daa5cd4f_fdab_4c45_a328_e468bc320a3f;

		public static void Serialize(Cube__char_32___char_40_37__char_41__61eafb88fd9d6194ba45b87da05ebf7d_Cube__char_46_SpawnTower_daa5cd4f_fdab_4c45_a328_e468bc320a3f commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_37__char_41__61eafb88fd9d6194ba45b87da05ebf7d_Cube__char_46_SpawnTower_daa5cd4f_fdab_4c45_a328_e468bc320a3f Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_37__char_41__61eafb88fd9d6194ba45b87da05ebf7d_Cube__char_46_SpawnTower_daa5cd4f_fdab_4c45_a328_e468bc320a3f
			(
			){};
		}
	}
}
