// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_27__char_41__1580ae4debff40d45a17004970d42efe_Cube__char_46_SpawnTower_64ae4464_af45_4a90_802b_cd96ecbb63b1 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_27__char_41__1580ae4debff40d45a17004970d42efe_Cube__char_46_SpawnTower_64ae4464_af45_4a90_802b_cd96ecbb63b1;

		public static void Serialize(Cube__char_32___char_40_27__char_41__1580ae4debff40d45a17004970d42efe_Cube__char_46_SpawnTower_64ae4464_af45_4a90_802b_cd96ecbb63b1 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_27__char_41__1580ae4debff40d45a17004970d42efe_Cube__char_46_SpawnTower_64ae4464_af45_4a90_802b_cd96ecbb63b1 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_27__char_41__1580ae4debff40d45a17004970d42efe_Cube__char_46_SpawnTower_64ae4464_af45_4a90_802b_cd96ecbb63b1
			(
			){};
		}
	}
}
