// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_SpawnTower_b51dab03_1455_4aca_9f24_cc3c3b57ec56 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_SpawnTower_b51dab03_1455_4aca_9f24_cc3c3b57ec56;

		public static void Serialize(Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_SpawnTower_b51dab03_1455_4aca_9f24_cc3c3b57ec56 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_SpawnTower_b51dab03_1455_4aca_9f24_cc3c3b57ec56 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_88__char_41__e24f61b7f9a8b5a4c821e1ac91731eec_Cube__char_46_SpawnTower_b51dab03_1455_4aca_9f24_cc3c3b57ec56
			(
			){};
		}
	}
}
