// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_114__char_41__1d70e71bb444f85449845ba2cd744f38_Cube__char_46_SpawnTower_668aa53a_ed8d_4029_8dfc_22eb4e3b6946 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_114__char_41__1d70e71bb444f85449845ba2cd744f38_Cube__char_46_SpawnTower_668aa53a_ed8d_4029_8dfc_22eb4e3b6946;

		public static void Serialize(Cube__char_32___char_40_114__char_41__1d70e71bb444f85449845ba2cd744f38_Cube__char_46_SpawnTower_668aa53a_ed8d_4029_8dfc_22eb4e3b6946 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_114__char_41__1d70e71bb444f85449845ba2cd744f38_Cube__char_46_SpawnTower_668aa53a_ed8d_4029_8dfc_22eb4e3b6946 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_114__char_41__1d70e71bb444f85449845ba2cd744f38_Cube__char_46_SpawnTower_668aa53a_ed8d_4029_8dfc_22eb4e3b6946
			(
			){};
		}
	}
}
