// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_86__char_41__90e27211466d89e4aa3f5c61fe55fba7_Cube__char_46_SpawnTower_764092a0_8fa1_4504_a16c_1407e0604bda : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_86__char_41__90e27211466d89e4aa3f5c61fe55fba7_Cube__char_46_SpawnTower_764092a0_8fa1_4504_a16c_1407e0604bda;

		public static void Serialize(Cube__char_32___char_40_86__char_41__90e27211466d89e4aa3f5c61fe55fba7_Cube__char_46_SpawnTower_764092a0_8fa1_4504_a16c_1407e0604bda commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_86__char_41__90e27211466d89e4aa3f5c61fe55fba7_Cube__char_46_SpawnTower_764092a0_8fa1_4504_a16c_1407e0604bda Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_86__char_41__90e27211466d89e4aa3f5c61fe55fba7_Cube__char_46_SpawnTower_764092a0_8fa1_4504_a16c_1407e0604bda
			(
			){};
		}
	}
}
