// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_98__char_41__de5eace782b819a4187367b25140757f_Cube__char_46_SpawnTower_75094cf0_c43e_4052_95e1_773889359d40 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_98__char_41__de5eace782b819a4187367b25140757f_Cube__char_46_SpawnTower_75094cf0_c43e_4052_95e1_773889359d40;

		public static void Serialize(Cube__char_32___char_40_98__char_41__de5eace782b819a4187367b25140757f_Cube__char_46_SpawnTower_75094cf0_c43e_4052_95e1_773889359d40 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_98__char_41__de5eace782b819a4187367b25140757f_Cube__char_46_SpawnTower_75094cf0_c43e_4052_95e1_773889359d40 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_98__char_41__de5eace782b819a4187367b25140757f_Cube__char_46_SpawnTower_75094cf0_c43e_4052_95e1_773889359d40
			(
			){};
		}
	}
}
