// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_28__char_41__7ad6bad542b2c2b4792a70cc43fb8ab2_Cube__char_46_SpawnTower_99fa4ea6_aecc_4c3b_8d76_37735dee246c : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_28__char_41__7ad6bad542b2c2b4792a70cc43fb8ab2_Cube__char_46_SpawnTower_99fa4ea6_aecc_4c3b_8d76_37735dee246c;

		public static void Serialize(Cube__char_32___char_40_28__char_41__7ad6bad542b2c2b4792a70cc43fb8ab2_Cube__char_46_SpawnTower_99fa4ea6_aecc_4c3b_8d76_37735dee246c commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_28__char_41__7ad6bad542b2c2b4792a70cc43fb8ab2_Cube__char_46_SpawnTower_99fa4ea6_aecc_4c3b_8d76_37735dee246c Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_28__char_41__7ad6bad542b2c2b4792a70cc43fb8ab2_Cube__char_46_SpawnTower_99fa4ea6_aecc_4c3b_8d76_37735dee246c
			(
			){};
		}
	}
}
