// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_92__char_41__0f727e91e6dd19741a190dc18258f90a_Cube__char_46_SpawnTower_33a3700a_c9e2_4e65_823b_cea071d8194c : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_92__char_41__0f727e91e6dd19741a190dc18258f90a_Cube__char_46_SpawnTower_33a3700a_c9e2_4e65_823b_cea071d8194c;

		public static void Serialize(Cube__char_32___char_40_92__char_41__0f727e91e6dd19741a190dc18258f90a_Cube__char_46_SpawnTower_33a3700a_c9e2_4e65_823b_cea071d8194c commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_92__char_41__0f727e91e6dd19741a190dc18258f90a_Cube__char_46_SpawnTower_33a3700a_c9e2_4e65_823b_cea071d8194c Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_92__char_41__0f727e91e6dd19741a190dc18258f90a_Cube__char_46_SpawnTower_33a3700a_c9e2_4e65_823b_cea071d8194c
			(
			){};
		}
	}
}
