// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_116__char_41__cdb2780dc4e1d82419902b2554b31e37_Cube__char_46_SpawnTower_9aee1946_7721_49d2_8121_bf3efb41e08f : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_116__char_41__cdb2780dc4e1d82419902b2554b31e37_Cube__char_46_SpawnTower_9aee1946_7721_49d2_8121_bf3efb41e08f;

		public static void Serialize(Cube__char_32___char_40_116__char_41__cdb2780dc4e1d82419902b2554b31e37_Cube__char_46_SpawnTower_9aee1946_7721_49d2_8121_bf3efb41e08f commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_116__char_41__cdb2780dc4e1d82419902b2554b31e37_Cube__char_46_SpawnTower_9aee1946_7721_49d2_8121_bf3efb41e08f Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_116__char_41__cdb2780dc4e1d82419902b2554b31e37_Cube__char_46_SpawnTower_9aee1946_7721_49d2_8121_bf3efb41e08f
			(
			){};
		}
	}
}
