// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_106__char_41__1d87d022db328164e8ff7bb1a03316ae_Cube__char_46_SpawnTower_8be7cd58_23f1_40aa_ad1c_ef09bafe46a8 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_106__char_41__1d87d022db328164e8ff7bb1a03316ae_Cube__char_46_SpawnTower_8be7cd58_23f1_40aa_ad1c_ef09bafe46a8;

		public static void Serialize(Cube__char_32___char_40_106__char_41__1d87d022db328164e8ff7bb1a03316ae_Cube__char_46_SpawnTower_8be7cd58_23f1_40aa_ad1c_ef09bafe46a8 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_106__char_41__1d87d022db328164e8ff7bb1a03316ae_Cube__char_46_SpawnTower_8be7cd58_23f1_40aa_ad1c_ef09bafe46a8 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_106__char_41__1d87d022db328164e8ff7bb1a03316ae_Cube__char_46_SpawnTower_8be7cd58_23f1_40aa_ad1c_ef09bafe46a8
			(
			){};
		}
	}
}
