// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_85__char_41__1055a46107062aa48b98b0bd040cf1e2_Cube__char_46_SpawnTower_02ed5bb2_1a68_4ed4_8730_803be549bb30 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_85__char_41__1055a46107062aa48b98b0bd040cf1e2_Cube__char_46_SpawnTower_02ed5bb2_1a68_4ed4_8730_803be549bb30;

		public static void Serialize(Cube__char_32___char_40_85__char_41__1055a46107062aa48b98b0bd040cf1e2_Cube__char_46_SpawnTower_02ed5bb2_1a68_4ed4_8730_803be549bb30 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_85__char_41__1055a46107062aa48b98b0bd040cf1e2_Cube__char_46_SpawnTower_02ed5bb2_1a68_4ed4_8730_803be549bb30 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_85__char_41__1055a46107062aa48b98b0bd040cf1e2_Cube__char_46_SpawnTower_02ed5bb2_1a68_4ed4_8730_803be549bb30
			(
			){};
		}
	}
}
