// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_97__char_41__217432b53ddd8cb4090891e87f9d5c64_Cube__char_46_SpawnTower_f84f27e3_5643_4d2c_8ffc_6046494d9a1e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_97__char_41__217432b53ddd8cb4090891e87f9d5c64_Cube__char_46_SpawnTower_f84f27e3_5643_4d2c_8ffc_6046494d9a1e;

		public static void Serialize(Cube__char_32___char_40_97__char_41__217432b53ddd8cb4090891e87f9d5c64_Cube__char_46_SpawnTower_f84f27e3_5643_4d2c_8ffc_6046494d9a1e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_97__char_41__217432b53ddd8cb4090891e87f9d5c64_Cube__char_46_SpawnTower_f84f27e3_5643_4d2c_8ffc_6046494d9a1e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_97__char_41__217432b53ddd8cb4090891e87f9d5c64_Cube__char_46_SpawnTower_f84f27e3_5643_4d2c_8ffc_6046494d9a1e
			(
			){};
		}
	}
}
