// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_87__char_41__df6efd32a72aef04bbc3d7eb4001e460_Cube__char_46_SpawnTower_b62c2931_a2b2_46a8_9495_dc04fab8a27d : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_87__char_41__df6efd32a72aef04bbc3d7eb4001e460_Cube__char_46_SpawnTower_b62c2931_a2b2_46a8_9495_dc04fab8a27d;

		public static void Serialize(Cube__char_32___char_40_87__char_41__df6efd32a72aef04bbc3d7eb4001e460_Cube__char_46_SpawnTower_b62c2931_a2b2_46a8_9495_dc04fab8a27d commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_87__char_41__df6efd32a72aef04bbc3d7eb4001e460_Cube__char_46_SpawnTower_b62c2931_a2b2_46a8_9495_dc04fab8a27d Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_87__char_41__df6efd32a72aef04bbc3d7eb4001e460_Cube__char_46_SpawnTower_b62c2931_a2b2_46a8_9495_dc04fab8a27d
			(
			){};
		}
	}
}
