// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_73__char_41__f60df34180df8d64a85442b584c2f38a_Cube__char_46_SpawnTower_cdf778d6_5eee_4be8_9928_a8e5a753021a : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_73__char_41__f60df34180df8d64a85442b584c2f38a_Cube__char_46_SpawnTower_cdf778d6_5eee_4be8_9928_a8e5a753021a;

		public static void Serialize(Cube__char_32___char_40_73__char_41__f60df34180df8d64a85442b584c2f38a_Cube__char_46_SpawnTower_cdf778d6_5eee_4be8_9928_a8e5a753021a commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_73__char_41__f60df34180df8d64a85442b584c2f38a_Cube__char_46_SpawnTower_cdf778d6_5eee_4be8_9928_a8e5a753021a Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_73__char_41__f60df34180df8d64a85442b584c2f38a_Cube__char_46_SpawnTower_cdf778d6_5eee_4be8_9928_a8e5a753021a
			(
			){};
		}
	}
}
