// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_40__char_41__a8f22ad56c921ed40a314fe4ecf2b6f9_Cube__char_46_SpawnTower_bd990e60_fdc6_4076_b4a1_53edd488eedf : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_40__char_41__a8f22ad56c921ed40a314fe4ecf2b6f9_Cube__char_46_SpawnTower_bd990e60_fdc6_4076_b4a1_53edd488eedf;

		public static void Serialize(Cube__char_32___char_40_40__char_41__a8f22ad56c921ed40a314fe4ecf2b6f9_Cube__char_46_SpawnTower_bd990e60_fdc6_4076_b4a1_53edd488eedf commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_40__char_41__a8f22ad56c921ed40a314fe4ecf2b6f9_Cube__char_46_SpawnTower_bd990e60_fdc6_4076_b4a1_53edd488eedf Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_40__char_41__a8f22ad56c921ed40a314fe4ecf2b6f9_Cube__char_46_SpawnTower_bd990e60_fdc6_4076_b4a1_53edd488eedf
			(
			){};
		}
	}
}
