// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_35__char_41__a9b400e682b9a844fbdfce503fe27d4d_Cube__char_46_SpawnTower_ce68636b_d5e3_483f_8463_d454821c792e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_35__char_41__a9b400e682b9a844fbdfce503fe27d4d_Cube__char_46_SpawnTower_ce68636b_d5e3_483f_8463_d454821c792e;

		public static void Serialize(Cube__char_32___char_40_35__char_41__a9b400e682b9a844fbdfce503fe27d4d_Cube__char_46_SpawnTower_ce68636b_d5e3_483f_8463_d454821c792e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_35__char_41__a9b400e682b9a844fbdfce503fe27d4d_Cube__char_46_SpawnTower_ce68636b_d5e3_483f_8463_d454821c792e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_35__char_41__a9b400e682b9a844fbdfce503fe27d4d_Cube__char_46_SpawnTower_ce68636b_d5e3_483f_8463_d454821c792e
			(
			){};
		}
	}
}
