// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_33__char_41__cfd65a8bdbccaa84eae3bd1e3f8f6af7_Cube__char_46_SpawnTower_9a10fb26_b263_4653_a3bd_de319c3e8f1e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_33__char_41__cfd65a8bdbccaa84eae3bd1e3f8f6af7_Cube__char_46_SpawnTower_9a10fb26_b263_4653_a3bd_de319c3e8f1e;

		public static void Serialize(Cube__char_32___char_40_33__char_41__cfd65a8bdbccaa84eae3bd1e3f8f6af7_Cube__char_46_SpawnTower_9a10fb26_b263_4653_a3bd_de319c3e8f1e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_33__char_41__cfd65a8bdbccaa84eae3bd1e3f8f6af7_Cube__char_46_SpawnTower_9a10fb26_b263_4653_a3bd_de319c3e8f1e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_33__char_41__cfd65a8bdbccaa84eae3bd1e3f8f6af7_Cube__char_46_SpawnTower_9a10fb26_b263_4653_a3bd_de319c3e8f1e
			(
			){};
		}
	}
}
