// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_99__char_41__1430ceb68c218ae40b54952c5358d862_Cube__char_46_SpawnTower_5399281e_b5e6_47b1_b271_34e773b4890b : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_99__char_41__1430ceb68c218ae40b54952c5358d862_Cube__char_46_SpawnTower_5399281e_b5e6_47b1_b271_34e773b4890b;

		public static void Serialize(Cube__char_32___char_40_99__char_41__1430ceb68c218ae40b54952c5358d862_Cube__char_46_SpawnTower_5399281e_b5e6_47b1_b271_34e773b4890b commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_99__char_41__1430ceb68c218ae40b54952c5358d862_Cube__char_46_SpawnTower_5399281e_b5e6_47b1_b271_34e773b4890b Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_99__char_41__1430ceb68c218ae40b54952c5358d862_Cube__char_46_SpawnTower_5399281e_b5e6_47b1_b271_34e773b4890b
			(
			){};
		}
	}
}
