// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_44__char_41__48f4cce54ac5c95429ac27e86b370bce_Cube__char_46_SpawnTower_c77e86b2_df42_4798_b09d_97502df20114 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_44__char_41__48f4cce54ac5c95429ac27e86b370bce_Cube__char_46_SpawnTower_c77e86b2_df42_4798_b09d_97502df20114;

		public static void Serialize(Cube__char_32___char_40_44__char_41__48f4cce54ac5c95429ac27e86b370bce_Cube__char_46_SpawnTower_c77e86b2_df42_4798_b09d_97502df20114 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_44__char_41__48f4cce54ac5c95429ac27e86b370bce_Cube__char_46_SpawnTower_c77e86b2_df42_4798_b09d_97502df20114 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_44__char_41__48f4cce54ac5c95429ac27e86b370bce_Cube__char_46_SpawnTower_c77e86b2_df42_4798_b09d_97502df20114
			(
			){};
		}
	}
}
