// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_115__char_41__85f5bcecebb8fb8489fe817c94e4c28d_Cube__char_46_SpawnTower_97d32c94_bddf_49ae_90a6_847b1bd60238 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_115__char_41__85f5bcecebb8fb8489fe817c94e4c28d_Cube__char_46_SpawnTower_97d32c94_bddf_49ae_90a6_847b1bd60238;

		public static void Serialize(Cube__char_32___char_40_115__char_41__85f5bcecebb8fb8489fe817c94e4c28d_Cube__char_46_SpawnTower_97d32c94_bddf_49ae_90a6_847b1bd60238 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_115__char_41__85f5bcecebb8fb8489fe817c94e4c28d_Cube__char_46_SpawnTower_97d32c94_bddf_49ae_90a6_847b1bd60238 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_115__char_41__85f5bcecebb8fb8489fe817c94e4c28d_Cube__char_46_SpawnTower_97d32c94_bddf_49ae_90a6_847b1bd60238
			(
			){};
		}
	}
}
