// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_105__char_41__0f6805b7d46c3b34090ae31d7ac9cc9c_Cube__char_46_SpawnTower_40bc68d8_eb63_4688_a050_f85ae3f2152e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_105__char_41__0f6805b7d46c3b34090ae31d7ac9cc9c_Cube__char_46_SpawnTower_40bc68d8_eb63_4688_a050_f85ae3f2152e;

		public static void Serialize(Cube__char_32___char_40_105__char_41__0f6805b7d46c3b34090ae31d7ac9cc9c_Cube__char_46_SpawnTower_40bc68d8_eb63_4688_a050_f85ae3f2152e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_105__char_41__0f6805b7d46c3b34090ae31d7ac9cc9c_Cube__char_46_SpawnTower_40bc68d8_eb63_4688_a050_f85ae3f2152e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_105__char_41__0f6805b7d46c3b34090ae31d7ac9cc9c_Cube__char_46_SpawnTower_40bc68d8_eb63_4688_a050_f85ae3f2152e
			(
			){};
		}
	}
}
