// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_29__char_41__898e9f0d5ed316d4eafde3e002106039_Cube__char_46_SpawnTower_6a24aa45_6676_4f27_95d8_7992b67f483c : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_29__char_41__898e9f0d5ed316d4eafde3e002106039_Cube__char_46_SpawnTower_6a24aa45_6676_4f27_95d8_7992b67f483c;

		public static void Serialize(Cube__char_32___char_40_29__char_41__898e9f0d5ed316d4eafde3e002106039_Cube__char_46_SpawnTower_6a24aa45_6676_4f27_95d8_7992b67f483c commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_29__char_41__898e9f0d5ed316d4eafde3e002106039_Cube__char_46_SpawnTower_6a24aa45_6676_4f27_95d8_7992b67f483c Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_29__char_41__898e9f0d5ed316d4eafde3e002106039_Cube__char_46_SpawnTower_6a24aa45_6676_4f27_95d8_7992b67f483c
			(
			){};
		}
	}
}
