// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_15__char_41__3b9c460ddb222b84d8256715b9eb0f18_Cube__char_46_SpawnTower_01087de1_a203_4ce5_b92a_9cd7b05f4ae8 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_15__char_41__3b9c460ddb222b84d8256715b9eb0f18_Cube__char_46_SpawnTower_01087de1_a203_4ce5_b92a_9cd7b05f4ae8;

		public static void Serialize(Cube__char_32___char_40_15__char_41__3b9c460ddb222b84d8256715b9eb0f18_Cube__char_46_SpawnTower_01087de1_a203_4ce5_b92a_9cd7b05f4ae8 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_15__char_41__3b9c460ddb222b84d8256715b9eb0f18_Cube__char_46_SpawnTower_01087de1_a203_4ce5_b92a_9cd7b05f4ae8 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_15__char_41__3b9c460ddb222b84d8256715b9eb0f18_Cube__char_46_SpawnTower_01087de1_a203_4ce5_b92a_9cd7b05f4ae8
			(
			){};
		}
	}
}
