// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_55__char_41__a55b3298c50828a4a88cd12bf0a09aed_Cube__char_46_SpawnTower_64a5c763_02eb_4c70_a429_8643404872a5 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_55__char_41__a55b3298c50828a4a88cd12bf0a09aed_Cube__char_46_SpawnTower_64a5c763_02eb_4c70_a429_8643404872a5;

		public static void Serialize(Cube__char_32___char_40_55__char_41__a55b3298c50828a4a88cd12bf0a09aed_Cube__char_46_SpawnTower_64a5c763_02eb_4c70_a429_8643404872a5 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_55__char_41__a55b3298c50828a4a88cd12bf0a09aed_Cube__char_46_SpawnTower_64a5c763_02eb_4c70_a429_8643404872a5 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_55__char_41__a55b3298c50828a4a88cd12bf0a09aed_Cube__char_46_SpawnTower_64a5c763_02eb_4c70_a429_8643404872a5
			(
			){};
		}
	}
}
