// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_75__char_41__8f85021cf4ffdbb47aeee35aefec93f1_Cube__char_46_SpawnTower_6d47fb3f_0a3c_40f6_8254_9c229c9805c6 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_75__char_41__8f85021cf4ffdbb47aeee35aefec93f1_Cube__char_46_SpawnTower_6d47fb3f_0a3c_40f6_8254_9c229c9805c6;

		public static void Serialize(Cube__char_32___char_40_75__char_41__8f85021cf4ffdbb47aeee35aefec93f1_Cube__char_46_SpawnTower_6d47fb3f_0a3c_40f6_8254_9c229c9805c6 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_75__char_41__8f85021cf4ffdbb47aeee35aefec93f1_Cube__char_46_SpawnTower_6d47fb3f_0a3c_40f6_8254_9c229c9805c6 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_75__char_41__8f85021cf4ffdbb47aeee35aefec93f1_Cube__char_46_SpawnTower_6d47fb3f_0a3c_40f6_8254_9c229c9805c6
			(
			){};
		}
	}
}
