// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_72__char_41__ffc7c83de3483bf48805776e15d072f5_Cube__char_46_SpawnTower_59c67dcc_da96_4143_8954_8878bddbb16e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_72__char_41__ffc7c83de3483bf48805776e15d072f5_Cube__char_46_SpawnTower_59c67dcc_da96_4143_8954_8878bddbb16e;

		public static void Serialize(Cube__char_32___char_40_72__char_41__ffc7c83de3483bf48805776e15d072f5_Cube__char_46_SpawnTower_59c67dcc_da96_4143_8954_8878bddbb16e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_72__char_41__ffc7c83de3483bf48805776e15d072f5_Cube__char_46_SpawnTower_59c67dcc_da96_4143_8954_8878bddbb16e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_72__char_41__ffc7c83de3483bf48805776e15d072f5_Cube__char_46_SpawnTower_59c67dcc_da96_4143_8954_8878bddbb16e
			(
			){};
		}
	}
}
