// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_36__char_41__124207d1c3f539b45b1d2865a2491267_Cube__char_46_SpawnTower_5661bcac_0ad4_4981_8f66_208a6f1683b0 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_36__char_41__124207d1c3f539b45b1d2865a2491267_Cube__char_46_SpawnTower_5661bcac_0ad4_4981_8f66_208a6f1683b0;

		public static void Serialize(Cube__char_32___char_40_36__char_41__124207d1c3f539b45b1d2865a2491267_Cube__char_46_SpawnTower_5661bcac_0ad4_4981_8f66_208a6f1683b0 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_36__char_41__124207d1c3f539b45b1d2865a2491267_Cube__char_46_SpawnTower_5661bcac_0ad4_4981_8f66_208a6f1683b0 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_36__char_41__124207d1c3f539b45b1d2865a2491267_Cube__char_46_SpawnTower_5661bcac_0ad4_4981_8f66_208a6f1683b0
			(
			){};
		}
	}
}
