// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_Dmg_42a614e9_e40b_4ccd_b672_ab7f48f037a3 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_Dmg_42a614e9_e40b_4ccd_b672_ab7f48f037a3;

		public static void Serialize(Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_Dmg_42a614e9_e40b_4ccd_b672_ab7f48f037a3 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_Dmg_42a614e9_e40b_4ccd_b672_ab7f48f037a3 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_2__char_41__ba7dad75247fdbf4891b7ddbc7934357_Health__char_46_Dmg_42a614e9_e40b_4ccd_b672_ab7f48f037a3
			(
			){};
		}
	}
}
