// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Cube__char_32___char_40_4__char_41__543d88115fcccf64588f14a989e67403_Cube__char_46_SpawnTower_01063c8c_585f_44ff_9c7c_2e5ed206208e : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalCube__char_32___char_40_4__char_41__543d88115fcccf64588f14a989e67403_Cube__char_46_SpawnTower_01063c8c_585f_44ff_9c7c_2e5ed206208e;

		public static void Serialize(Cube__char_32___char_40_4__char_41__543d88115fcccf64588f14a989e67403_Cube__char_46_SpawnTower_01063c8c_585f_44ff_9c7c_2e5ed206208e commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Cube__char_32___char_40_4__char_41__543d88115fcccf64588f14a989e67403_Cube__char_46_SpawnTower_01063c8c_585f_44ff_9c7c_2e5ed206208e Deserialize(IInProtocolBitStream bitStream)
		{

			return new Cube__char_32___char_40_4__char_41__543d88115fcccf64588f14a989e67403_Cube__char_46_SpawnTower_01063c8c_585f_44ff_9c7c_2e5ed206208e
			(
			){};
		}
	}
}
