// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.SimulationFrame;
	using Coherence.Entity;
	using Coherence.Utils;
	using Coherence.Brook;
	using Coherence.Toolkit;
	using UnityEngine;

	public struct CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739 : ICoherenceComponentData
	{
		public int towerCredits;
		public int enemyCredits;

		public override string ToString()
		{
			return $"CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739(towerCredits: {towerCredits}, enemyCredits: {enemyCredits})";
		}

		public uint GetComponentType() => Definition.InternalCurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739;

		public const int order = 0;

		public uint FieldsMask => 0b00000000000000000000000000000011;

		public int GetComponentOrder() => order;
		public bool IsSendOrdered() { return false; }

		public AbsoluteSimulationFrame Frame;
	
		private static readonly int _towerCredits_Min = -2147483648;
		private static readonly int _towerCredits_Max = 2147483647;
		private static readonly int _enemyCredits_Min = -2147483648;
		private static readonly int _enemyCredits_Max = 2147483647;

		public void SetSimulationFrame(AbsoluteSimulationFrame frame)
		{
			Frame = frame;
		}

		public AbsoluteSimulationFrame GetSimulationFrame() => Frame;

		public ICoherenceComponentData MergeWith(ICoherenceComponentData data, uint mask)
		{
			var other = (CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739)data;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				towerCredits = other.towerCredits;
			}
			mask >>= 1;
			if ((mask & 0x01) != 0)
			{
				Frame = other.Frame;
				enemyCredits = other.enemyCredits;
			}
			mask >>= 1;
			return this;
		}

		public uint DiffWith(ICoherenceComponentData data)
		{
			throw new System.NotSupportedException($"{nameof(DiffWith)} is not supported in Unity");

		}

		public static uint Serialize(CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739 data, uint mask, IOutProtocolBitStream bitStream)
		{
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.towerCredits, _towerCredits_Min, _towerCredits_Max, "CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739.towerCredits");
				data.towerCredits = Coherence.Utils.Bounds.Clamp(data.towerCredits, _towerCredits_Min, _towerCredits_Max);
				var fieldValue = data.towerCredits;

				bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
			}
			mask >>= 1;
			if (bitStream.WriteMask((mask & 0x01) != 0))
			{
				Coherence.Utils.Bounds.Check(data.enemyCredits, _enemyCredits_Min, _enemyCredits_Max, "CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739.enemyCredits");
				data.enemyCredits = Coherence.Utils.Bounds.Clamp(data.enemyCredits, _enemyCredits_Min, _enemyCredits_Max);
				var fieldValue = data.enemyCredits;

				bitStream.WriteIntegerRange(fieldValue, 32, -2147483648);
			}
			mask >>= 1;

			return mask;
		}

		public static (CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739, uint) Deserialize(InProtocolBitStream bitStream)
		{
			var mask = (uint)0;
			var val = new CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739();
	
			if (bitStream.ReadMask())
			{
				val.towerCredits = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000001;
			}
			if (bitStream.ReadMask())
			{
				val.enemyCredits = bitStream.ReadIntegerRange(32, -2147483648);
				mask |= 0b00000000000000000000000000000010;
			}
			return (val, mask);
		}

		/// <summary>
		/// Resets byte array references to the local array instance that is kept in the lastSentData.
		/// If the array content has changed but remains of same length, the new content is copied into the local array instance.
		/// If the array length has changed, the array is cloned and overwrites the local instance.
		/// If the array has not changed, the reference is reset to the local array instance.
		/// Otherwise, changes to other fields on the component might cause the local array instance reference to become permanently lost.
		/// </summary>
		public void ResetByteArrays(ICoherenceComponentData lastSent, uint mask)
		{
			var last = lastSent as CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_CurrencyManager_509801874849245739?;
	
		}
	}
}