// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input : IEntityInput
	{
		public uint GetComponentType() => Definition.InternalCurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input;

		private readonly bool isRemoteInput;

		public CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input Deserialize(IInProtocolBitStream bitStream)
		{

			return new CurrencyManager_48bcb4c0de4c0864e9e7802bb437dc7d_Input
			(
				true
			);
		}
	}
}
