// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;
	using Coherence.Entity;

	public struct Enemy_13805883eac76884398e87131a7f0bcc_EnemyAI__char_46_Move_1d968d1f_fbf3_4180_ab74_3bf8526f0c09 : IEntityCommand
	{

		public MessageTarget Routing => MessageTarget.All;
		public uint GetComponentType() => Definition.InternalEnemy_13805883eac76884398e87131a7f0bcc_EnemyAI__char_46_Move_1d968d1f_fbf3_4180_ab74_3bf8526f0c09;

		public static void Serialize(Enemy_13805883eac76884398e87131a7f0bcc_EnemyAI__char_46_Move_1d968d1f_fbf3_4180_ab74_3bf8526f0c09 commandData, IOutProtocolBitStream bitStream)
		{
		}

		public static Enemy_13805883eac76884398e87131a7f0bcc_EnemyAI__char_46_Move_1d968d1f_fbf3_4180_ab74_3bf8526f0c09 Deserialize(IInProtocolBitStream bitStream)
		{

			return new Enemy_13805883eac76884398e87131a7f0bcc_EnemyAI__char_46_Move_1d968d1f_fbf3_4180_ab74_3bf8526f0c09
			(
			){};
		}
	}
}
