// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using Coherence.ProtocolDef;
	using Coherence.Serializer;
	using Coherence.Brook;
	using UnityEngine;

	public struct PlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input : IEntityInput
	{
		public uint GetComponentType() => Definition.InternalPlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input;

		private readonly bool isRemoteInput;

		public PlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input
		(
			bool isRemoteInput
		)
		{
			this.isRemoteInput = isRemoteInput;
		}

		public override string ToString()
		{
			return isRemoteInput
				? $""
				: $"";
		}

		public static void Serialize(PlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input inputData, IOutProtocolBitStream bitStream)
		{
		}

		public static PlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input Deserialize(IInProtocolBitStream bitStream)
		{

			return new PlayerSpawner_b7e2e07e36fde7340a26947bb8451106_Input
			(
				true
			);
		}
	}
}
